-- cms_deid.sql: Deidentify CMS data
-- Copyright (c) 2017 University of Kansas Medical Center

insert /*+ APPEND */ into "&&deid_schema".outpatient_condition_codes
select /*+ PARALLEL(outpatient_condition_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_COND_CD_SEQ,
  idt.CLM_RLT_COND_CD
from outpatient_condition_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".maxdata_ps
select /*+ PARALLEL(maxdata_ps,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MSIS_ID,
  idt.STATE_CD,
  idt.EL_STATE_CASE_NUM,
  idt.MAX_YR_DT,
  idt.HGT_FLAG,
  idt.EXT_SSN_SRCE,
  idt.EL_DOB + bm.date_shift_days EL_DOB,
  idt.EL_AGE_GRP_CD,
  idt.EL_SEX_CD,
  idt.EL_RACE_ETHNCY_CD,
  idt.RACE_CODE_1,
  idt.RACE_CODE_2,
  idt.RACE_CODE_3,
  idt.RACE_CODE_4,
  idt.RACE_CODE_5,
  idt.ETHNICITY_CODE,
  idt.MDCR_RACE_ETHNCY_CD,
  idt.MDCR_LANG_CD,
  idt.EL_SEX_RACE_CD,
  idt.EL_DOD + bm.date_shift_days EL_DOD,
  idt.MDCR_DOD + bm.date_shift_days MDCR_DOD,
  idt.MDCR_DEATH_DAY_SW,
  idt.EL_RSDNC_CNTY_CD_LTST,
  NULL EL_RSDNC_ZIP_CD_LTST,
  idt.EL_SS_ELGBLTY_CD_LTST,
  idt.EL_MAX_ELGBLTY_CD_LTST,
  idt.MSNG_ELG_DATA,
  idt.EL_ELGBLTY_MO_CNT,
  idt.EL_PRVT_INSRNC_MO_CNT,
  idt.EL_MDCR_ANN_XOVR_OLD,
  idt.EL_MDCR_QTR_XOVR_OLD_1,
  idt.EL_MDCR_QTR_XOVR_OLD_2,
  idt.EL_MDCR_QTR_XOVR_OLD_3,
  idt.EL_MDCR_QTR_XOVR_OLD_4,
  idt.EL_MDCR_DUAL_ANN,
  idt.EL_MDCR_QTR_XOVR_99_1,
  idt.EL_MDCR_QTR_XOVR_99_2,
  idt.EL_MDCR_QTR_XOVR_99_3,
  idt.EL_MDCR_QTR_XOVR_99_4,
  idt.EL_MDCR_BEN_MO_CNT,
  idt.MDCR_ORIG_REAS_CD,
  idt.EL_MDCR_DUAL_MO_1,
  idt.EL_MDCR_DUAL_MO_2,
  idt.EL_MDCR_DUAL_MO_3,
  idt.EL_MDCR_DUAL_MO_4,
  idt.EL_MDCR_DUAL_MO_5,
  idt.EL_MDCR_DUAL_MO_6,
  idt.EL_MDCR_DUAL_MO_7,
  idt.EL_MDCR_DUAL_MO_8,
  idt.EL_MDCR_DUAL_MO_9,
  idt.EL_MDCR_DUAL_MO_10,
  idt.EL_MDCR_DUAL_MO_11,
  idt.EL_MDCR_DUAL_MO_12,
  idt.SS_ELG_CD_MO_1,
  idt.SS_ELG_CD_MO_2,
  idt.SS_ELG_CD_MO_3,
  idt.SS_ELG_CD_MO_4,
  idt.SS_ELG_CD_MO_5,
  idt.SS_ELG_CD_MO_6,
  idt.SS_ELG_CD_MO_7,
  idt.SS_ELG_CD_MO_8,
  idt.SS_ELG_CD_MO_9,
  idt.SS_ELG_CD_MO_10,
  idt.SS_ELG_CD_MO_11,
  idt.SS_ELG_CD_MO_12,
  idt.MAX_ELG_CD_MO_1,
  idt.MAX_ELG_CD_MO_2,
  idt.MAX_ELG_CD_MO_3,
  idt.MAX_ELG_CD_MO_4,
  idt.MAX_ELG_CD_MO_5,
  idt.MAX_ELG_CD_MO_6,
  idt.MAX_ELG_CD_MO_7,
  idt.MAX_ELG_CD_MO_8,
  idt.MAX_ELG_CD_MO_9,
  idt.MAX_ELG_CD_MO_10,
  idt.MAX_ELG_CD_MO_11,
  idt.MAX_ELG_CD_MO_12,
  idt.EL_PVT_INS_CD_1,
  idt.EL_PVT_INS_CD_2,
  idt.EL_PVT_INS_CD_3,
  idt.EL_PVT_INS_CD_4,
  idt.EL_PVT_INS_CD_5,
  idt.EL_PVT_INS_CD_6,
  idt.EL_PVT_INS_CD_7,
  idt.EL_PVT_INS_CD_8,
  idt.EL_PVT_INS_CD_9,
  idt.EL_PVT_INS_CD_10,
  idt.EL_PVT_INS_CD_11,
  idt.EL_PVT_INS_CD_12,
  idt.EL_MDCR_BEN_MO_1,
  idt.EL_MDCR_BEN_MO_2,
  idt.EL_MDCR_BEN_MO_3,
  idt.EL_MDCR_BEN_MO_4,
  idt.EL_MDCR_BEN_MO_5,
  idt.EL_MDCR_BEN_MO_6,
  idt.EL_MDCR_BEN_MO_7,
  idt.EL_MDCR_BEN_MO_8,
  idt.EL_MDCR_BEN_MO_9,
  idt.EL_MDCR_BEN_MO_10,
  idt.EL_MDCR_BEN_MO_11,
  idt.EL_MDCR_BEN_MO_12,
  idt.EL_PPH_PLN_MO_CNT_CMCP,
  idt.EL_PPH_PLN_MO_CNT_DMCP,
  idt.EL_PPH_PLN_MO_CNT_BMCP,
  idt.EL_PPH_PLN_MO_CNT_PDMC,
  idt.EL_PPH_PLN_MO_CNT_LTCM,
  idt.EL_PPH_PLN_MO_CNT_AICE,
  idt.EL_PPH_PLN_MO_CNT_PCCM,
  idt.EL_PHP_TYPE_1_1,
  idt.EL_PHP_ID_1_1,
  idt.EL_PHP_TYPE_2_1,
  idt.EL_PHP_ID_2_1,
  idt.EL_PHP_TYPE_3_1,
  idt.EL_PHP_ID_3_1,
  idt.EL_PHP_TYPE_4_1,
  idt.EL_PHP_ID_4_1,
  idt.EL_PHP_TYPE_1_2,
  idt.EL_PHP_ID_1_2,
  idt.EL_PHP_TYPE_2_2,
  idt.EL_PHP_ID_2_2,
  idt.EL_PHP_TYPE_3_2,
  idt.EL_PHP_ID_3_2,
  idt.EL_PHP_TYPE_4_2,
  idt.EL_PHP_ID_4_2,
  idt.EL_PHP_TYPE_1_3,
  idt.EL_PHP_ID_1_3,
  idt.EL_PHP_TYPE_2_3,
  idt.EL_PHP_ID_2_3,
  idt.EL_PHP_TYPE_3_3,
  idt.EL_PHP_ID_3_3,
  idt.EL_PHP_TYPE_4_3,
  idt.EL_PHP_ID_4_3,
  idt.EL_PHP_TYPE_1_4,
  idt.EL_PHP_ID_1_4,
  idt.EL_PHP_TYPE_2_4,
  idt.EL_PHP_ID_2_4,
  idt.EL_PHP_TYPE_3_4,
  idt.EL_PHP_ID_3_4,
  idt.EL_PHP_TYPE_4_4,
  idt.EL_PHP_ID_4_4,
  idt.EL_PHP_TYPE_1_5,
  idt.EL_PHP_ID_1_5,
  idt.EL_PHP_TYPE_2_5,
  idt.EL_PHP_ID_2_5,
  idt.EL_PHP_TYPE_3_5,
  idt.EL_PHP_ID_3_5,
  idt.EL_PHP_TYPE_4_5,
  idt.EL_PHP_ID_4_5,
  idt.EL_PHP_TYPE_1_6,
  idt.EL_PHP_ID_1_6,
  idt.EL_PHP_TYPE_2_6,
  idt.EL_PHP_ID_2_6,
  idt.EL_PHP_TYPE_3_6,
  idt.EL_PHP_ID_3_6,
  idt.EL_PHP_TYPE_4_6,
  idt.EL_PHP_ID_4_6,
  idt.EL_PHP_TYPE_1_7,
  idt.EL_PHP_ID_1_7,
  idt.EL_PHP_TYPE_2_7,
  idt.EL_PHP_ID_2_7,
  idt.EL_PHP_TYPE_3_7,
  idt.EL_PHP_ID_3_7,
  idt.EL_PHP_TYPE_4_7,
  idt.EL_PHP_ID_4_7,
  idt.EL_PHP_TYPE_1_8,
  idt.EL_PHP_ID_1_8,
  idt.EL_PHP_TYPE_2_8,
  idt.EL_PHP_ID_2_8,
  idt.EL_PHP_TYPE_3_8,
  idt.EL_PHP_ID_3_8,
  idt.EL_PHP_TYPE_4_8,
  idt.EL_PHP_ID_4_8,
  idt.EL_PHP_TYPE_1_9,
  idt.EL_PHP_ID_1_9,
  idt.EL_PHP_TYPE_2_9,
  idt.EL_PHP_ID_2_9,
  idt.EL_PHP_TYPE_3_9,
  idt.EL_PHP_ID_3_9,
  idt.EL_PHP_TYPE_4_9,
  idt.EL_PHP_ID_4_9,
  idt.EL_PHP_TYPE_1_10,
  idt.EL_PHP_ID_1_10,
  idt.EL_PHP_TYPE_2_10,
  idt.EL_PHP_ID_2_10,
  idt.EL_PHP_TYPE_3_10,
  idt.EL_PHP_ID_3_10,
  idt.EL_PHP_TYPE_4_10,
  idt.EL_PHP_ID_4_10,
  idt.EL_PHP_TYPE_1_11,
  idt.EL_PHP_ID_1_11,
  idt.EL_PHP_TYPE_2_11,
  idt.EL_PHP_ID_2_11,
  idt.EL_PHP_TYPE_3_11,
  idt.EL_PHP_ID_3_11,
  idt.EL_PHP_TYPE_4_11,
  idt.EL_PHP_ID_4_11,
  idt.EL_PHP_TYPE_1_12,
  idt.EL_PHP_ID_1_12,
  idt.EL_PHP_TYPE_2_12,
  idt.EL_PHP_ID_2_12,
  idt.EL_PHP_TYPE_3_12,
  idt.EL_PHP_ID_3_12,
  idt.EL_PHP_TYPE_4_12,
  idt.EL_PHP_ID_4_12,
  idt.MC_COMBO_MO_1,
  idt.MC_COMBO_MO_2,
  idt.MC_COMBO_MO_3,
  idt.MC_COMBO_MO_4,
  idt.MC_COMBO_MO_5,
  idt.MC_COMBO_MO_6,
  idt.MC_COMBO_MO_7,
  idt.MC_COMBO_MO_8,
  idt.MC_COMBO_MO_9,
  idt.MC_COMBO_MO_10,
  idt.MC_COMBO_MO_11,
  idt.MC_COMBO_MO_12,
  idt.EL_DAYS_EL_CNT_1,
  idt.EL_DAYS_EL_CNT_2,
  idt.EL_DAYS_EL_CNT_3,
  idt.EL_DAYS_EL_CNT_4,
  idt.EL_DAYS_EL_CNT_5,
  idt.EL_DAYS_EL_CNT_6,
  idt.EL_DAYS_EL_CNT_7,
  idt.EL_DAYS_EL_CNT_8,
  idt.EL_DAYS_EL_CNT_9,
  idt.EL_DAYS_EL_CNT_10,
  idt.EL_DAYS_EL_CNT_11,
  idt.EL_DAYS_EL_CNT_12,
  idt.EL_TANF_CASH_FLG_1,
  idt.EL_TANF_CASH_FLG_2,
  idt.EL_TANF_CASH_FLG_3,
  idt.EL_TANF_CASH_FLG_4,
  idt.EL_TANF_CASH_FLG_5,
  idt.EL_TANF_CASH_FLG_6,
  idt.EL_TANF_CASH_FLG_7,
  idt.EL_TANF_CASH_FLG_8,
  idt.EL_TANF_CASH_FLG_9,
  idt.EL_TANF_CASH_FLG_10,
  idt.EL_TANF_CASH_FLG_11,
  idt.EL_TANF_CASH_FLG_12,
  idt.EL_RSTRCT_BNFT_FLG_1,
  idt.EL_RSTRCT_BNFT_FLG_2,
  idt.EL_RSTRCT_BNFT_FLG_3,
  idt.EL_RSTRCT_BNFT_FLG_4,
  idt.EL_RSTRCT_BNFT_FLG_5,
  idt.EL_RSTRCT_BNFT_FLG_6,
  idt.EL_RSTRCT_BNFT_FLG_7,
  idt.EL_RSTRCT_BNFT_FLG_8,
  idt.EL_RSTRCT_BNFT_FLG_9,
  idt.EL_RSTRCT_BNFT_FLG_10,
  idt.EL_RSTRCT_BNFT_FLG_11,
  idt.EL_RSTRCT_BNFT_FLG_12,
  idt.EL_CHIP_FLAG_1,
  idt.EL_CHIP_FLAG_2,
  idt.EL_CHIP_FLAG_3,
  idt.EL_CHIP_FLAG_4,
  idt.EL_CHIP_FLAG_5,
  idt.EL_CHIP_FLAG_6,
  idt.EL_CHIP_FLAG_7,
  idt.EL_CHIP_FLAG_8,
  idt.EL_CHIP_FLAG_9,
  idt.EL_CHIP_FLAG_10,
  idt.EL_CHIP_FLAG_11,
  idt.EL_CHIP_FLAG_12,
  idt.MAX_WAIVER_TYPE_1_MO_1,
  idt.MAX_WAIVER_ID_1_MO_1,
  idt.MAX_WAIVER_TYPE_2_MO_1,
  idt.MAX_WAIVER_ID_2_MO_1,
  idt.MAX_WAIVER_TYPE_3_MO_1,
  idt.MAX_WAIVER_ID_3_MO_1,
  idt.MAX_WAIVER_TYPE_1_MO_2,
  idt.MAX_WAIVER_ID_1_MO_2,
  idt.MAX_WAIVER_TYPE_2_MO_2,
  idt.MAX_WAIVER_ID_2_MO_2,
  idt.MAX_WAIVER_TYPE_3_MO_2,
  idt.MAX_WAIVER_ID_3_MO_2,
  idt.MAX_WAIVER_TYPE_1_MO_3,
  idt.MAX_WAIVER_ID_1_MO_3,
  idt.MAX_WAIVER_TYPE_2_MO_3,
  idt.MAX_WAIVER_ID_2_MO_3,
  idt.MAX_WAIVER_TYPE_3_MO_3,
  idt.MAX_WAIVER_ID_3_MO_3,
  idt.MAX_WAIVER_TYPE_1_MO_4,
  idt.MAX_WAIVER_ID_1_MO_4,
  idt.MAX_WAIVER_TYPE_2_MO_4,
  idt.MAX_WAIVER_ID_2_MO_4,
  idt.MAX_WAIVER_TYPE_3_MO_4,
  idt.MAX_WAIVER_ID_3_MO_4,
  idt.MAX_WAIVER_TYPE_1_MO_5,
  idt.MAX_WAIVER_ID_1_MO_5,
  idt.MAX_WAIVER_TYPE_2_MO_5,
  idt.MAX_WAIVER_ID_2_MO_5,
  idt.MAX_WAIVER_TYPE_3_MO_5,
  idt.MAX_WAIVER_ID_3_MO_5,
  idt.MAX_WAIVER_TYPE_1_MO_6,
  idt.MAX_WAIVER_ID_1_MO_6,
  idt.MAX_WAIVER_TYPE_2_MO_6,
  idt.MAX_WAIVER_ID_2_MO_6,
  idt.MAX_WAIVER_TYPE_3_MO_6,
  idt.MAX_WAIVER_ID_3_MO_6,
  idt.MAX_WAIVER_TYPE_1_MO_7,
  idt.MAX_WAIVER_ID_1_MO_7,
  idt.MAX_WAIVER_TYPE_2_MO_7,
  idt.MAX_WAIVER_ID_2_MO_7,
  idt.MAX_WAIVER_TYPE_3_MO_7,
  idt.MAX_WAIVER_ID_3_MO_7,
  idt.MAX_WAIVER_TYPE_1_MO_8,
  idt.MAX_WAIVER_ID_1_MO_8,
  idt.MAX_WAIVER_TYPE_2_MO_8,
  idt.MAX_WAIVER_ID_2_MO_8,
  idt.MAX_WAIVER_TYPE_3_MO_8,
  idt.MAX_WAIVER_ID_3_MO_8,
  idt.MAX_WAIVER_TYPE_1_MO_9,
  idt.MAX_WAIVER_ID_1_MO_9,
  idt.MAX_WAIVER_TYPE_2_MO_9,
  idt.MAX_WAIVER_ID_2_MO_9,
  idt.MAX_WAIVER_TYPE_3_MO_9,
  idt.MAX_WAIVER_ID_3_MO_9,
  idt.MAX_WAIVER_TYPE_1_MO_10,
  idt.MAX_WAIVER_ID_1_MO_10,
  idt.MAX_WAIVER_TYPE_2_MO_10,
  idt.MAX_WAIVER_ID_2_MO_10,
  idt.MAX_WAIVER_TYPE_3_MO_10,
  idt.MAX_WAIVER_ID_3_MO_10,
  idt.MAX_WAIVER_TYPE_1_MO_11,
  idt.MAX_WAIVER_ID_1_MO_11,
  idt.MAX_WAIVER_TYPE_2_MO_11,
  idt.MAX_WAIVER_ID_2_MO_11,
  idt.MAX_WAIVER_TYPE_3_MO_11,
  idt.MAX_WAIVER_ID_3_MO_11,
  idt.MAX_WAIVER_TYPE_1_MO_12,
  idt.MAX_WAIVER_ID_1_MO_12,
  idt.MAX_WAIVER_TYPE_2_MO_12,
  idt.MAX_WAIVER_ID_2_MO_12,
  idt.MAX_WAIVER_TYPE_3_MO_12,
  idt.MAX_WAIVER_ID_3_MO_12,
  idt.MAX_1915C_WAIVER_TYPE_LTST,
  idt.RCPNT_IND,
  idt.TOT_IP_DSCHRG_CNT,
  idt.TOT_IP_STAY_CNT,
  idt.TOT_IP_DAY_CNT_DSCHRG,
  idt.TOT_IP_DAY_CNT_STAYS,
  idt.TOT_IP_CVR_DAY_CNT_DSCHRG,
  idt.TOT_IP_CVR_DAY_CNT_STAYS,
  idt.TOT_LTC_CVR_DAY_CNT_AGED,
  idt.TOT_LTC_CVR_DAY_CNT_PSYCH,
  idt.TOT_LTC_CVR_DAY_CNT_ICFMR,
  idt.TOT_LTC_CVR_DAY_CNT_NF,
  idt.TOT_LTC_CVR_DAY_CNT,
  idt.TOT_MDCD_CLM_CNT,
  idt.TOT_MDCD_FFS_CLM_CNT,
  idt.TOT_MDCD_PREM_CLM_CNT,
  idt.TOT_MDCD_ENCT_CLM_CNT,
  idt.TOT_MDCD_PYMT_AMT,
  idt.TOT_MDCD_FFS_PYMT_AMT,
  idt.TOT_MDCD_PREM_PYMT_AMT,
  idt.TOT_MDCD_CHRG_AMT,
  idt.TOT_MDCD_TP_PYMT_AMT,
  idt.IP_HOSP_REC_FP,
  idt.IP_HOSP_PYMT_FP,
  idt.LT_REC_CNT_FP,
  idt.LT_PYMT_AMT_FP,
  idt.OT_REC_CNT_FP,
  idt.OT_PYMT_AMT_FP,
  idt.RX_REC_CNT_FP,
  idt.RX_PYMT_AMT_FP,
  idt.TOT_REC_CNT_FP,
  idt.TOT_PYMT_AMT_FP,
  idt.IP_HOSP_REC_RHC,
  idt.IP_HOSP_PYMT_RHC,
  idt.LT_REC_CNT_RHC,
  idt.LT_PYMT_AMT_RHC,
  idt.OT_REC_CNT_RHC,
  idt.OT_PYMT_AMT_RHC,
  idt.RX_REC_CNT_RHC,
  idt.RX_PYMT_AMT_RHC,
  idt.TOT_REC_CNT_RHC,
  idt.TOT_PYMT_AMT_RHC,
  idt.IP_HOSP_REC_FQHC,
  idt.IP_HOSP_PYMT_FQHC,
  idt.LT_REC_CNT_FQHC,
  idt.LT_PYMT_AMT_FQHC,
  idt.OT_REC_CNT_FQHC,
  idt.OT_PYMT_AMT_FQHC,
  idt.RX_REC_CNT_FQHC,
  idt.RX_PYMT_AMT_FQHC,
  idt.TOT_REC_CNT_FQHC,
  idt.TOT_PYMT_AMT_FQHC,
  idt.IP_HOSP_REC_IHS,
  idt.IP_HOSP_PYMT_IHS,
  idt.LT_REC_CNT_IHS,
  idt.LT_PYMT_AMT_IHS,
  idt.OT_REC_CNT_IHS,
  idt.OT_PYMT_AMT_IHS,
  idt.RX_REC_CNT_IHS,
  idt.RX_PYMT_AMT_IHS,
  idt.TOT_REC_CNT_IHS,
  idt.TOT_PYMT_AMT_IHS,
  idt.IP_HOSP_REC_HCBCA,
  idt.IP_HOSP_PYMT_HCBCA,
  idt.LT_REC_CNT_HCBCA,
  idt.LT_PYMT_AMT_HCBCA,
  idt.OT_REC_CNT_HCBCA,
  idt.OT_PYMT_AMT_HCBCA,
  idt.RX_REC_CNT_HCBCA,
  idt.RX_PYMT_AMT_HCBCA,
  idt.TOT_REC_CNT_HCBCA,
  idt.TOT_PYMT_AMT_HCBCA,
  idt.IP_HOSP_REC_HCBCS,
  idt.IP_HOSP_PYMT_HCBCS,
  idt.LT_REC_CNT_HCBCS,
  idt.LT_PYMT_AMT_HCBCS,
  idt.OT_REC_CNT_HCBCS,
  idt.OT_PYMT_AMT_HCBCS,
  idt.RX_REC_CNT_HCBCS,
  idt.RX_PYMT_AMT_HCBCS,
  idt.TOT_REC_CNT_HCBCS,
  idt.TOT_PYMT_AMT_HCBCS,
  idt.RCPNT_DLVRY_CD,
  idt.FEE_FOR_SRVC_IND_01,
  idt.FFS_CLM_CNT_01,
  idt.FFS_PYMT_AMT_01,
  idt.FFS_CHRG_AMT_01,
  idt.FFS_TP_AMT_01,
  idt.ENCTR_REC_CNT_01,
  idt.FEE_FOR_SRVC_IND_02,
  idt.FFS_CLM_CNT_02,
  idt.FFS_PYMT_AMT_02,
  idt.FFS_CHRG_AMT_02,
  idt.FFS_TP_AMT_02,
  idt.ENCTR_REC_CNT_02,
  idt.FEE_FOR_SRVC_IND_04,
  idt.FFS_CLM_CNT_04,
  idt.FFS_PYMT_AMT_04,
  idt.FFS_CHRG_AMT_04,
  idt.FFS_TP_AMT_04,
  idt.ENCTR_REC_CNT_04,
  idt.FEE_FOR_SRVC_IND_05,
  idt.FFS_CLM_CNT_05,
  idt.FFS_PYMT_AMT_05,
  idt.FFS_CHRG_AMT_05,
  idt.FFS_TP_AMT_05,
  idt.ENCTR_REC_CNT_05,
  idt.FEE_FOR_SRVC_IND_07,
  idt.FFS_CLM_CNT_07,
  idt.FFS_PYMT_AMT_07,
  idt.FFS_CHRG_AMT_07,
  idt.FFS_TP_AMT_07,
  idt.ENCTR_REC_CNT_07,
  idt.FEE_FOR_SRVC_IND_08,
  idt.FFS_CLM_CNT_08,
  idt.FFS_PYMT_AMT_08,
  idt.FFS_CHRG_AMT_08,
  idt.FFS_TP_AMT_08,
  idt.ENCTR_REC_CNT_08,
  idt.FEE_FOR_SRVC_IND_09,
  idt.FFS_CLM_CNT_09,
  idt.FFS_PYMT_AMT_09,
  idt.FFS_CHRG_AMT_09,
  idt.FFS_TP_AMT_09,
  idt.ENCTR_REC_CNT_09,
  idt.FEE_FOR_SRVC_IND_10,
  idt.FFS_CLM_CNT_10,
  idt.FFS_PYMT_AMT_10,
  idt.FFS_CHRG_AMT_10,
  idt.FFS_TP_AMT_10,
  idt.ENCTR_REC_CNT_10,
  idt.FEE_FOR_SRVC_IND_11,
  idt.FFS_CLM_CNT_11,
  idt.FFS_PYMT_AMT_11,
  idt.FFS_CHRG_AMT_11,
  idt.FFS_TP_AMT_11,
  idt.ENCTR_REC_CNT_11,
  idt.FEE_FOR_SRVC_IND_12,
  idt.FFS_CLM_CNT_12,
  idt.FFS_PYMT_AMT_12,
  idt.FFS_CHRG_AMT_12,
  idt.FFS_TP_AMT_12,
  idt.ENCTR_REC_CNT_12,
  idt.FEE_FOR_SRVC_IND_13,
  idt.FFS_CLM_CNT_13,
  idt.FFS_PYMT_AMT_13,
  idt.FFS_CHRG_AMT_13,
  idt.FFS_TP_AMT_13,
  idt.ENCTR_REC_CNT_13,
  idt.FEE_FOR_SRVC_IND_15,
  idt.FFS_CLM_CNT_15,
  idt.FFS_PYMT_AMT_15,
  idt.FFS_CHRG_AMT_15,
  idt.FFS_TP_AMT_15,
  idt.ENCTR_REC_CNT_15,
  idt.FEE_FOR_SRVC_IND_16,
  idt.FFS_CLM_CNT_16,
  idt.FFS_PYMT_AMT_16,
  idt.FFS_CHRG_AMT_16,
  idt.FFS_TP_AMT_16,
  idt.ENCTR_REC_CNT_16,
  idt.FEE_FOR_SRVC_IND_19,
  idt.FFS_CLM_CNT_19,
  idt.FFS_PYMT_AMT_19,
  idt.FFS_CHRG_AMT_19,
  idt.FFS_TP_AMT_19,
  idt.ENCTR_REC_CNT_19,
  idt.FEE_FOR_SRVC_IND_24,
  idt.FFS_CLM_CNT_24,
  idt.FFS_PYMT_AMT_24,
  idt.FFS_CHRG_AMT_24,
  idt.FFS_TP_AMT_24,
  idt.ENCTR_REC_CNT_24,
  idt.FEE_FOR_SRVC_IND_25,
  idt.FFS_CLM_CNT_25,
  idt.FFS_PYMT_AMT_25,
  idt.FFS_CHRG_AMT_25,
  idt.FFS_TP_AMT_25,
  idt.ENCTR_REC_CNT_25,
  idt.FEE_FOR_SRVC_IND_26,
  idt.FFS_CLM_CNT_26,
  idt.FFS_PYMT_AMT_26,
  idt.FFS_CHRG_AMT_26,
  idt.FFS_TP_AMT_26,
  idt.ENCTR_REC_CNT_26,
  idt.FEE_FOR_SRVC_IND_30,
  idt.FFS_CLM_CNT_30,
  idt.FFS_PYMT_AMT_30,
  idt.FFS_CHRG_AMT_30,
  idt.FFS_TP_AMT_30,
  idt.ENCTR_REC_CNT_30,
  idt.FEE_FOR_SRVC_IND_31,
  idt.FFS_CLM_CNT_31,
  idt.FFS_PYMT_AMT_31,
  idt.FFS_CHRG_AMT_31,
  idt.FFS_TP_AMT_31,
  idt.ENCTR_REC_CNT_31,
  idt.FEE_FOR_SRVC_IND_33,
  idt.FFS_CLM_CNT_33,
  idt.FFS_PYMT_AMT_33,
  idt.FFS_CHRG_AMT_33,
  idt.FFS_TP_AMT_33,
  idt.ENCTR_REC_CNT_33,
  idt.FEE_FOR_SRVC_IND_34,
  idt.FFS_CLM_CNT_34,
  idt.FFS_PYMT_AMT_34,
  idt.FFS_CHRG_AMT_34,
  idt.FFS_TP_AMT_34,
  idt.ENCTR_REC_CNT_34,
  idt.FEE_FOR_SRVC_IND_35,
  idt.FFS_CLM_CNT_35,
  idt.FFS_PYMT_AMT_35,
  idt.FFS_CHRG_AMT_35,
  idt.FFS_TP_AMT_35,
  idt.ENCTR_REC_CNT_35,
  idt.FEE_FOR_SRVC_IND_36,
  idt.FFS_CLM_CNT_36,
  idt.FFS_PYMT_AMT_36,
  idt.FFS_CHRG_AMT_36,
  idt.FFS_TP_AMT_36,
  idt.ENCTR_REC_CNT_36,
  idt.FEE_FOR_SRVC_IND_37,
  idt.FFS_CLM_CNT_37,
  idt.FFS_PYMT_AMT_37,
  idt.FFS_CHRG_AMT_37,
  idt.FFS_TP_AMT_37,
  idt.ENCTR_REC_CNT_37,
  idt.FEE_FOR_SRVC_IND_38,
  idt.FFS_CLM_CNT_38,
  idt.FFS_PYMT_AMT_38,
  idt.FFS_CHRG_AMT_38,
  idt.FFS_TP_AMT_38,
  idt.ENCTR_REC_CNT_38,
  idt.FEE_FOR_SRVC_IND_39,
  idt.FFS_CLM_CNT_39,
  idt.FFS_PYMT_AMT_39,
  idt.FFS_CHRG_AMT_39,
  idt.FFS_TP_AMT_39,
  idt.ENCTR_REC_CNT_39,
  idt.FEE_FOR_SRVC_IND_51,
  idt.FFS_CLM_CNT_51,
  idt.FFS_PYMT_AMT_51,
  idt.FFS_CHRG_AMT_51,
  idt.FFS_TP_AMT_51,
  idt.ENCTR_REC_CNT_51,
  idt.FEE_FOR_SRVC_IND_52,
  idt.FFS_CLM_CNT_52,
  idt.FFS_PYMT_AMT_52,
  idt.FFS_CHRG_AMT_52,
  idt.FFS_TP_AMT_52,
  idt.ENCTR_REC_CNT_52,
  idt.FEE_FOR_SRVC_IND_53,
  idt.FFS_CLM_CNT_53,
  idt.FFS_PYMT_AMT_53,
  idt.FFS_CHRG_AMT_53,
  idt.FFS_TP_AMT_53,
  idt.ENCTR_REC_CNT_53,
  idt.FEE_FOR_SRVC_IND_54,
  idt.FFS_CLM_CNT_54,
  idt.FFS_PYMT_AMT_54,
  idt.FFS_CHRG_AMT_54,
  idt.FFS_TP_AMT_54,
  idt.ENCTR_REC_CNT_54,
  idt.FEE_FOR_SRVC_IND_99,
  idt.FFS_CLM_CNT_99,
  idt.FFS_PYMT_AMT_99,
  idt.FFS_CHRG_AMT_99,
  idt.FFS_TP_AMT_99,
  idt.ENCTR_REC_CNT_99,
  idt.CLTC_FFS_PYMT_AMT_11,
  idt.CLTC_FFS_PYMT_AMT_12,
  idt.CLTC_FFS_PYMT_AMT_13,
  idt.CLTC_FFS_PYMT_AMT_14,
  idt.CLTC_FFS_PYMT_AMT_15,
  idt.CLTC_FFS_PYMT_AMT_16,
  idt.CLTC_FFS_PYMT_AMT_17,
  idt.CLTC_FFS_PYMT_AMT_18,
  idt.CLTC_FFS_PYMT_AMT_19,
  idt.CLTC_FFS_PYMT_AMT_20,
  idt.CLTC_FFS_PYMT_AMT_30,
  idt.CLTC_FFS_PYMT_AMT_31,
  idt.CLTC_FFS_PYMT_AMT_32,
  idt.CLTC_FFS_PYMT_AMT_33,
  idt.CLTC_FFS_PYMT_AMT_34,
  idt.CLTC_FFS_PYMT_AMT_35,
  idt.CLTC_FFS_PYMT_AMT_36,
  idt.CLTC_FFS_PYMT_AMT_37,
  idt.CLTC_FFS_PYMT_AMT_38,
  idt.CLTC_FFS_PYMT_AMT_39,
  idt.CLTC_FFS_PYMT_AMT_40,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_01,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_02,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_03,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_04,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_05,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_06,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_07,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_08,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_09,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_10,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_11,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_12,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_13,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_14,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_15,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_16,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_17,
  idt.HCBS_TXNMY_MDCD_PYMT_AMT_18,
  idt.PREM_PYMT_IND_HMO,
  idt.PREM_PYMT_REC_CNT_HMO,
  idt.PREM_MDCD_PYMT_AMT_HMO,
  idt.PREM_PYMT_IND_PHP,
  idt.PREM_PYMT_REC_CNT_PHP,
  idt.PREM_MDCD_PYMT_AMT_PHP,
  idt.PREM_PYMT_IND_PCCM,
  idt.PREM_PYMT_REC_CNT_PCCM,
  idt.PREM_MDCD_PYMT_AMT_PCCM,
  idt.SSA_DOD + bm.date_shift_days SSA_DOD,
  idt.EL_MDCR_ANN_XOVR_99,
  idt.EL_MDCR_XOVR_MO_1,
  idt.EL_MDCR_XOVR_MO_2,
  idt.EL_MDCR_XOVR_MO_3,
  idt.EL_MDCR_XOVR_MO_4,
  idt.EL_MDCR_XOVR_MO_5,
  idt.EL_MDCR_XOVR_MO_6,
  idt.EL_MDCR_XOVR_MO_7,
  idt.EL_MDCR_XOVR_MO_8,
  idt.EL_MDCR_XOVR_MO_9,
  idt.EL_MDCR_XOVR_MO_10,
  idt.EL_MDCR_XOVR_MO_11,
  idt.EL_MDCR_XOVR_MO_12
from maxdata_ps idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".outpatient_occurrnce_codes
select /*+ PARALLEL(outpatient_occurrnce_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_OCRNC_CD_SEQ,
  idt.CLM_RLT_OCRNC_CD,
  idt.CLM_RLT_OCRNC_DT + bm.date_shift_days CLM_RLT_OCRNC_DT
from outpatient_occurrnce_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".outpatient_base_claims
select /*+ PARALLEL(outpatient_base_claims,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_NEAR_LINE_REC_IDENT_CD,
  idt.NCH_CLM_TYPE_CD,
  idt.CLM_FROM_DT + bm.date_shift_days CLM_FROM_DT,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.NCH_WKLY_PROC_DT + bm.date_shift_days NCH_WKLY_PROC_DT,
  idt.FI_CLM_PROC_DT + bm.date_shift_days FI_CLM_PROC_DT,
  idt.CLAIM_QUERY_CODE,
  idt.PRVDR_NUM,
  idt.CLM_FAC_TYPE_CD,
  idt.CLM_SRVC_CLSFCTN_TYPE_CD,
  idt.CLM_FREQ_CD,
  idt.FI_NUM,
  idt.CLM_MDCR_NON_PMT_RSN_CD,
  idt.CLM_PMT_AMT,
  idt.NCH_PRMRY_PYR_CLM_PD_AMT,
  idt.NCH_PRMRY_PYR_CD,
  idt.PRVDR_STATE_CD,
  idt.ORG_NPI_NUM,
  idt.AT_PHYSN_UPIN,
  idt.AT_PHYSN_NPI,
  idt.OP_PHYSN_UPIN,
  idt.OP_PHYSN_NPI,
  idt.OT_PHYSN_UPIN,
  idt.OT_PHYSN_NPI,
  idt.CLM_MCO_PD_SW,
  idt.PTNT_DSCHRG_STUS_CD,
  idt.CLM_TOT_CHRG_AMT,
  idt.NCH_BENE_BLOOD_DDCTBL_LBLTY_AM,
  idt.NCH_PROFNL_CMPNT_CHRG_AMT,
  idt.PRNCPAL_DGNS_CD,
  idt.PRNCPAL_DGNS_VRSN_CD,
  idt.ICD_DGNS_CD1,
  idt.ICD_DGNS_VRSN_CD1,
  idt.ICD_DGNS_CD2,
  idt.ICD_DGNS_VRSN_CD2,
  idt.ICD_DGNS_CD3,
  idt.ICD_DGNS_VRSN_CD3,
  idt.ICD_DGNS_CD4,
  idt.ICD_DGNS_VRSN_CD4,
  idt.ICD_DGNS_CD5,
  idt.ICD_DGNS_VRSN_CD5,
  idt.ICD_DGNS_CD6,
  idt.ICD_DGNS_VRSN_CD6,
  idt.ICD_DGNS_CD7,
  idt.ICD_DGNS_VRSN_CD7,
  idt.ICD_DGNS_CD8,
  idt.ICD_DGNS_VRSN_CD8,
  idt.ICD_DGNS_CD9,
  idt.ICD_DGNS_VRSN_CD9,
  idt.ICD_DGNS_CD10,
  idt.ICD_DGNS_VRSN_CD10,
  idt.ICD_DGNS_CD11,
  idt.ICD_DGNS_VRSN_CD11,
  idt.ICD_DGNS_CD12,
  idt.ICD_DGNS_VRSN_CD12,
  idt.ICD_DGNS_CD13,
  idt.ICD_DGNS_VRSN_CD13,
  idt.ICD_DGNS_CD14,
  idt.ICD_DGNS_VRSN_CD14,
  idt.ICD_DGNS_CD15,
  idt.ICD_DGNS_VRSN_CD15,
  idt.ICD_DGNS_CD16,
  idt.ICD_DGNS_VRSN_CD16,
  idt.ICD_DGNS_CD17,
  idt.ICD_DGNS_VRSN_CD17,
  idt.ICD_DGNS_CD18,
  idt.ICD_DGNS_VRSN_CD18,
  idt.ICD_DGNS_CD19,
  idt.ICD_DGNS_VRSN_CD19,
  idt.ICD_DGNS_CD20,
  idt.ICD_DGNS_VRSN_CD20,
  idt.ICD_DGNS_CD21,
  idt.ICD_DGNS_VRSN_CD21,
  idt.ICD_DGNS_CD22,
  idt.ICD_DGNS_VRSN_CD22,
  idt.ICD_DGNS_CD23,
  idt.ICD_DGNS_VRSN_CD23,
  idt.ICD_DGNS_CD24,
  idt.ICD_DGNS_VRSN_CD24,
  idt.ICD_DGNS_CD25,
  idt.ICD_DGNS_VRSN_CD25,
  idt.FST_DGNS_E_CD,
  idt.FST_DGNS_E_VRSN_CD,
  idt.ICD_DGNS_E_CD1,
  idt.ICD_DGNS_E_VRSN_CD1,
  idt.ICD_DGNS_E_CD2,
  idt.ICD_DGNS_E_VRSN_CD2,
  idt.ICD_DGNS_E_CD3,
  idt.ICD_DGNS_E_VRSN_CD3,
  idt.ICD_DGNS_E_CD4,
  idt.ICD_DGNS_E_VRSN_CD4,
  idt.ICD_DGNS_E_CD5,
  idt.ICD_DGNS_E_VRSN_CD5,
  idt.ICD_DGNS_E_CD6,
  idt.ICD_DGNS_E_VRSN_CD6,
  idt.ICD_DGNS_E_CD7,
  idt.ICD_DGNS_E_VRSN_CD7,
  idt.ICD_DGNS_E_CD8,
  idt.ICD_DGNS_E_VRSN_CD8,
  idt.ICD_DGNS_E_CD9,
  idt.ICD_DGNS_E_VRSN_CD9,
  idt.ICD_DGNS_E_CD10,
  idt.ICD_DGNS_E_VRSN_CD10,
  idt.ICD_DGNS_E_CD11,
  idt.ICD_DGNS_E_VRSN_CD11,
  idt.ICD_DGNS_E_CD12,
  idt.ICD_DGNS_E_VRSN_CD12,
  idt.ICD_PRCDR_CD1,
  idt.ICD_PRCDR_VRSN_CD1,
  idt.PRCDR_DT1 + bm.date_shift_days PRCDR_DT1,
  idt.ICD_PRCDR_CD2,
  idt.ICD_PRCDR_VRSN_CD2,
  idt.PRCDR_DT2 + bm.date_shift_days PRCDR_DT2,
  idt.ICD_PRCDR_CD3,
  idt.ICD_PRCDR_VRSN_CD3,
  idt.PRCDR_DT3 + bm.date_shift_days PRCDR_DT3,
  idt.ICD_PRCDR_CD4,
  idt.ICD_PRCDR_VRSN_CD4,
  idt.PRCDR_DT4 + bm.date_shift_days PRCDR_DT4,
  idt.ICD_PRCDR_CD5,
  idt.ICD_PRCDR_VRSN_CD5,
  idt.PRCDR_DT5 + bm.date_shift_days PRCDR_DT5,
  idt.ICD_PRCDR_CD6,
  idt.ICD_PRCDR_VRSN_CD6,
  idt.PRCDR_DT6 + bm.date_shift_days PRCDR_DT6,
  idt.ICD_PRCDR_CD7,
  idt.ICD_PRCDR_VRSN_CD7,
  idt.PRCDR_DT7 + bm.date_shift_days PRCDR_DT7,
  idt.ICD_PRCDR_CD8,
  idt.ICD_PRCDR_VRSN_CD8,
  idt.PRCDR_DT8 + bm.date_shift_days PRCDR_DT8,
  idt.ICD_PRCDR_CD9,
  idt.ICD_PRCDR_VRSN_CD9,
  idt.PRCDR_DT9 + bm.date_shift_days PRCDR_DT9,
  idt.ICD_PRCDR_CD10,
  idt.ICD_PRCDR_VRSN_CD10,
  idt.PRCDR_DT10 + bm.date_shift_days PRCDR_DT10,
  idt.ICD_PRCDR_CD11,
  idt.ICD_PRCDR_VRSN_CD11,
  idt.PRCDR_DT11 + bm.date_shift_days PRCDR_DT11,
  idt.ICD_PRCDR_CD12,
  idt.ICD_PRCDR_VRSN_CD12,
  idt.PRCDR_DT12 + bm.date_shift_days PRCDR_DT12,
  idt.ICD_PRCDR_CD13,
  idt.ICD_PRCDR_VRSN_CD13,
  idt.PRCDR_DT13 + bm.date_shift_days PRCDR_DT13,
  idt.ICD_PRCDR_CD14,
  idt.ICD_PRCDR_VRSN_CD14,
  idt.PRCDR_DT14 + bm.date_shift_days PRCDR_DT14,
  idt.ICD_PRCDR_CD15,
  idt.ICD_PRCDR_VRSN_CD15,
  idt.PRCDR_DT15 + bm.date_shift_days PRCDR_DT15,
  idt.ICD_PRCDR_CD16,
  idt.ICD_PRCDR_VRSN_CD16,
  idt.PRCDR_DT16 + bm.date_shift_days PRCDR_DT16,
  idt.ICD_PRCDR_CD17,
  idt.ICD_PRCDR_VRSN_CD17,
  idt.PRCDR_DT17 + bm.date_shift_days PRCDR_DT17,
  idt.ICD_PRCDR_CD18,
  idt.ICD_PRCDR_VRSN_CD18,
  idt.PRCDR_DT18 + bm.date_shift_days PRCDR_DT18,
  idt.ICD_PRCDR_CD19,
  idt.ICD_PRCDR_VRSN_CD19,
  idt.PRCDR_DT19 + bm.date_shift_days PRCDR_DT19,
  idt.ICD_PRCDR_CD20,
  idt.ICD_PRCDR_VRSN_CD20,
  idt.PRCDR_DT20 + bm.date_shift_days PRCDR_DT20,
  idt.ICD_PRCDR_CD21,
  idt.ICD_PRCDR_VRSN_CD21,
  idt.PRCDR_DT21 + bm.date_shift_days PRCDR_DT21,
  idt.ICD_PRCDR_CD22,
  idt.ICD_PRCDR_VRSN_CD22,
  idt.PRCDR_DT22 + bm.date_shift_days PRCDR_DT22,
  idt.ICD_PRCDR_CD23,
  idt.ICD_PRCDR_VRSN_CD23,
  idt.PRCDR_DT23 + bm.date_shift_days PRCDR_DT23,
  idt.ICD_PRCDR_CD24,
  idt.ICD_PRCDR_VRSN_CD24,
  idt.PRCDR_DT24 + bm.date_shift_days PRCDR_DT24,
  idt.ICD_PRCDR_CD25,
  idt.ICD_PRCDR_VRSN_CD25,
  idt.PRCDR_DT25 + bm.date_shift_days PRCDR_DT25,
  idt.RSN_VISIT_CD1,
  idt.RSN_VISIT_VRSN_CD1,
  idt.RSN_VISIT_CD2,
  idt.RSN_VISIT_VRSN_CD2,
  idt.RSN_VISIT_CD3,
  idt.RSN_VISIT_VRSN_CD3,
  idt.NCH_BENE_PTB_DDCTBL_AMT,
  idt.NCH_BENE_PTB_COINSRNC_AMT,
  idt.CLM_OP_PRVDR_PMT_AMT,
  idt.CLM_OP_BENE_PMT_AMT,
  idt.DOB_DT + bm.date_shift_days DOB_DT,
  idt.GNDR_CD,
  idt.BENE_RACE_CD,
  idt.BENE_CNTY_CD,
  idt.BENE_STATE_CD,
  NULL BENE_MLG_CNTCT_ZIP_CD,
  idt.CLM_MDCL_REC
from outpatient_base_claims idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_base_claims
select /*+ PARALLEL(hospice_base_claims,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_NEAR_LINE_REC_IDENT_CD,
  idt.NCH_CLM_TYPE_CD,
  idt.CLM_FROM_DT + bm.date_shift_days CLM_FROM_DT,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.NCH_WKLY_PROC_DT + bm.date_shift_days NCH_WKLY_PROC_DT,
  idt.FI_CLM_PROC_DT + bm.date_shift_days FI_CLM_PROC_DT,
  idt.PRVDR_NUM,
  idt.CLM_FAC_TYPE_CD,
  idt.CLM_SRVC_CLSFCTN_TYPE_CD,
  idt.CLM_FREQ_CD,
  idt.FI_NUM,
  idt.CLM_MDCR_NON_PMT_RSN_CD,
  idt.CLM_PMT_AMT,
  idt.NCH_PRMRY_PYR_CLM_PD_AMT,
  idt.NCH_PRMRY_PYR_CD,
  idt.PRVDR_STATE_CD,
  idt.ORG_NPI_NUM,
  idt.AT_PHYSN_UPIN,
  idt.AT_PHYSN_NPI,
  idt.PTNT_DSCHRG_STUS_CD,
  idt.CLM_TOT_CHRG_AMT,
  idt.NCH_PTNT_STATUS_IND_CD,
  idt.CLM_UTLZTN_DAY_CNT,
  idt.NCH_BENE_DSCHRG_DT + bm.date_shift_days NCH_BENE_DSCHRG_DT,
  idt.PRNCPAL_DGNS_CD,
  idt.PRNCPAL_DGNS_VRSN_CD,
  idt.ICD_DGNS_CD1,
  idt.ICD_DGNS_VRSN_CD1,
  idt.ICD_DGNS_CD2,
  idt.ICD_DGNS_VRSN_CD2,
  idt.ICD_DGNS_CD3,
  idt.ICD_DGNS_VRSN_CD3,
  idt.ICD_DGNS_CD4,
  idt.ICD_DGNS_VRSN_CD4,
  idt.ICD_DGNS_CD5,
  idt.ICD_DGNS_VRSN_CD5,
  idt.ICD_DGNS_CD6,
  idt.ICD_DGNS_VRSN_CD6,
  idt.ICD_DGNS_CD7,
  idt.ICD_DGNS_VRSN_CD7,
  idt.ICD_DGNS_CD8,
  idt.ICD_DGNS_VRSN_CD8,
  idt.ICD_DGNS_CD9,
  idt.ICD_DGNS_VRSN_CD9,
  idt.ICD_DGNS_CD10,
  idt.ICD_DGNS_VRSN_CD10,
  idt.ICD_DGNS_CD11,
  idt.ICD_DGNS_VRSN_CD11,
  idt.ICD_DGNS_CD12,
  idt.ICD_DGNS_VRSN_CD12,
  idt.ICD_DGNS_CD13,
  idt.ICD_DGNS_VRSN_CD13,
  idt.ICD_DGNS_CD14,
  idt.ICD_DGNS_VRSN_CD14,
  idt.ICD_DGNS_CD15,
  idt.ICD_DGNS_VRSN_CD15,
  idt.ICD_DGNS_CD16,
  idt.ICD_DGNS_VRSN_CD16,
  idt.ICD_DGNS_CD17,
  idt.ICD_DGNS_VRSN_CD17,
  idt.ICD_DGNS_CD18,
  idt.ICD_DGNS_VRSN_CD18,
  idt.ICD_DGNS_CD19,
  idt.ICD_DGNS_VRSN_CD19,
  idt.ICD_DGNS_CD20,
  idt.ICD_DGNS_VRSN_CD20,
  idt.ICD_DGNS_CD21,
  idt.ICD_DGNS_VRSN_CD21,
  idt.ICD_DGNS_CD22,
  idt.ICD_DGNS_VRSN_CD22,
  idt.ICD_DGNS_CD23,
  idt.ICD_DGNS_VRSN_CD23,
  idt.ICD_DGNS_CD24,
  idt.ICD_DGNS_VRSN_CD24,
  idt.ICD_DGNS_CD25,
  idt.ICD_DGNS_VRSN_CD25,
  idt.FST_DGNS_E_CD,
  idt.FST_DGNS_E_VRSN_CD,
  idt.ICD_DGNS_E_CD1,
  idt.ICD_DGNS_E_VRSN_CD1,
  idt.ICD_DGNS_E_CD2,
  idt.ICD_DGNS_E_VRSN_CD2,
  idt.ICD_DGNS_E_CD3,
  idt.ICD_DGNS_E_VRSN_CD3,
  idt.ICD_DGNS_E_CD4,
  idt.ICD_DGNS_E_VRSN_CD4,
  idt.ICD_DGNS_E_CD5,
  idt.ICD_DGNS_E_VRSN_CD5,
  idt.ICD_DGNS_E_CD6,
  idt.ICD_DGNS_E_VRSN_CD6,
  idt.ICD_DGNS_E_CD7,
  idt.ICD_DGNS_E_VRSN_CD7,
  idt.ICD_DGNS_E_CD8,
  idt.ICD_DGNS_E_VRSN_CD8,
  idt.ICD_DGNS_E_CD9,
  idt.ICD_DGNS_E_VRSN_CD9,
  idt.ICD_DGNS_E_CD10,
  idt.ICD_DGNS_E_VRSN_CD10,
  idt.ICD_DGNS_E_CD11,
  idt.ICD_DGNS_E_VRSN_CD11,
  idt.ICD_DGNS_E_CD12,
  idt.ICD_DGNS_E_VRSN_CD12,
  idt.CLM_HOSPC_START_DT_ID + bm.date_shift_days CLM_HOSPC_START_DT_ID,
  idt.BENE_HOSPC_PRD_CNT,
  idt.DOB_DT + bm.date_shift_days DOB_DT,
  idt.GNDR_CD,
  idt.BENE_RACE_CD,
  idt.BENE_CNTY_CD,
  idt.BENE_STATE_CD,
  NULL BENE_MLG_CNTCT_ZIP_CD,
  idt.CLM_MDCL_REC
from hospice_base_claims idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".outpatient_span_codes
select /*+ PARALLEL(outpatient_span_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_SPAN_CD_SEQ,
  idt.CLM_SPAN_CD,
  idt.CLM_SPAN_FROM_DT + bm.date_shift_days CLM_SPAN_FROM_DT,
  idt.CLM_SPAN_THRU_DT + bm.date_shift_days CLM_SPAN_THRU_DT
from outpatient_span_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".maxdata_ot
select /*+ PARALLEL(maxdata_ot,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MSIS_ID,
  idt.STATE_CD,
  idt.YR_NUM,
  idt.EL_DOB + bm.date_shift_days EL_DOB,
  idt.EL_SEX_CD,
  idt.EL_RACE_ETHNCY_CD,
  idt.RACE_CODE_1,
  idt.RACE_CODE_2,
  idt.RACE_CODE_3,
  idt.RACE_CODE_4,
  idt.RACE_CODE_5,
  idt.ETHNICITY_CODE,
  idt.EL_SS_ELGBLTY_CD_LTST,
  idt.EL_SS_ELGBLTY_CD_MO,
  idt.EL_MAX_ELGBLTY_CD_LTST,
  idt.EL_MAX_ELGBLTY_CD_MO,
  idt.EL_MDCR_ANN_XOVR_OLD,
  idt.MSNG_ELG_DATA,
  idt.EL_MDCR_XOVR_CLM_BSD_CD,
  idt.EL_MDCR_ANN_XOVR_99,
  idt.MSIS_TOS,
  idt.MSIS_TOP,
  idt.HCBS_TXNMY_WVR_CD,
  idt.MAX_TOS,
  idt.CLTC_FLAG,
  idt.PRVDR_ID_NMBR,
  idt.NPI,
  idt.TAXONOMY,
  idt.TYPE_CLM_CD,
  idt.ADJUST_CD,
  idt.PHP_TYPE,
  idt.PHP_ID,
  idt.MDCD_PYMT_AMT,
  idt.TP_PYMT_AMT,
  idt.PYMT_DT + bm.date_shift_days PYMT_DT,
  idt.CHRG_AMT,
  idt.PHP_VAL,
  idt.MDCR_COINSUR_PYMT_AMT,
  idt.MDCR_DED_PYMT_AMT,
  idt.SRVC_BGN_DT + bm.date_shift_days SRVC_BGN_DT,
  idt.SRVC_END_DT + bm.date_shift_days SRVC_END_DT,
  idt.PRCDR_CD_SYS,
  idt.PRCDR_CD,
  idt.PRCDR_SRVC_MDFR_CD,
  idt.DIAG_CD_1,
  idt.DIAG_CD_2,
  idt.QTY_SRVC_UNITS,
  idt.SRVC_PRVDR_ID_NMBR,
  idt.SRVC_PRVDR_SPEC_CD,
  idt.PLC_OF_SRVC_CD,
  idt.UB_92_REV_CD
from maxdata_ot idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".mbsf_ab_summary
select /*+ PARALLEL(mbsf_ab_summary,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.BENE_ENROLLMT_REF_YR,
  idt.FIVE_PERCENT_FLAG,
  idt.ENHANCED_FIVE_PERCENT_FLAG,
  idt.COVSTART + bm.date_shift_days COVSTART,
  idt.CRNT_BIC_CD,
  idt.STATE_CODE,
  NULL BENE_COUNTY_CD,
  NULL BENE_ZIP_CD,
  idt.BENE_AGE_AT_END_REF_YR,
  idt.BENE_BIRTH_DT + bm.date_shift_days BENE_BIRTH_DT,
  idt.BENE_VALID_DEATH_DT_SW,
  idt.BENE_DEATH_DT + bm.date_shift_days BENE_DEATH_DT,
  idt.NDI_DEATH_DT + bm.date_shift_days NDI_DEATH_DT,
  idt.BENE_SEX_IDENT_CD,
  idt.BENE_RACE_CD,
  idt.RTI_RACE_CD,
  idt.BENE_ENTLMT_RSN_ORIG,
  idt.BENE_ENTLMT_RSN_CURR,
  idt.BENE_ESRD_IND,
  idt.BENE_MDCR_STATUS_CD,
  idt.BENE_PTA_TRMNTN_CD,
  idt.BENE_PTB_TRMNTN_CD,
  idt.BENE_HI_CVRAGE_TOT_MONS,
  idt.BENE_SMI_CVRAGE_TOT_MONS,
  idt.BENE_STATE_BUYIN_TOT_MONS,
  idt.BENE_HMO_CVRAGE_TOT_MONS,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_01,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_02,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_03,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_04,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_05,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_06,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_07,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_08,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_09,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_10,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_11,
  idt.BENE_MDCR_ENTLMT_BUYIN_IND_12,
  idt.BENE_HMO_IND_01,
  idt.BENE_HMO_IND_02,
  idt.BENE_HMO_IND_03,
  idt.BENE_HMO_IND_04,
  idt.BENE_HMO_IND_05,
  idt.BENE_HMO_IND_06,
  idt.BENE_HMO_IND_07,
  idt.BENE_HMO_IND_08,
  idt.BENE_HMO_IND_09,
  idt.BENE_HMO_IND_10,
  idt.BENE_HMO_IND_11,
  idt.BENE_HMO_IND_12
from mbsf_ab_summary idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".medpar_all
select /*+ PARALLEL(medpar_all,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MEDPAR_ID,
  idt.MEDPAR_YR_NUM,
  idt.NCH_CLM_TYPE_CD,
  idt.BENE_IDENT_CD,
  idt.EQTBL_BIC_CD,
  idt.BENE_AGE_CNT,
  idt.BENE_SEX_CD,
  idt.BENE_RACE_CD,
  idt.BENE_MDCR_STUS_CD,
  idt.BENE_RSDNC_SSA_STATE_CD,
  idt.BENE_RSDNC_SSA_CNTY_CD,
  NULL BENE_MLG_CNTCT_ZIP_CD,
  idt.BENE_DSCHRG_STUS_CD,
  idt.FICARR_IDENT_NUM,
  idt.WRNG_IND_CD,
  idt.GHO_PD_CD,
  idt.PPS_IND_CD,
  idt.ORG_NPI_NUM,
  idt.PRVDR_NUM,
  idt.PRVDR_NUM_SPCL_UNIT_CD,
  idt.SS_LS_SNF_IND_CD,
  idt.ACTV_XREF_IND,
  idt.SLCT_RSN_CD,
  idt.STAY_FINL_ACTN_CLM_CNT,
  idt.LTST_CLM_ACRTN_DT + bm.date_shift_days LTST_CLM_ACRTN_DT,
  idt.BENE_MDCR_BNFT_EXHST_DT + bm.date_shift_days BENE_MDCR_BNFT_EXHST_DT,
  idt.SNF_QUALN_FROM_DT + bm.date_shift_days SNF_QUALN_FROM_DT,
  idt.SNF_QUALN_THRU_DT + bm.date_shift_days SNF_QUALN_THRU_DT,
  idt.SRC_IP_ADMSN_CD,
  idt.IP_ADMSN_TYPE_CD,
  idt.ADMSN_DAY_CD,
  idt.ADMSN_DT + bm.date_shift_days ADMSN_DT,
  idt.DSCHRG_DT + bm.date_shift_days DSCHRG_DT,
  idt.DSCHRG_DSTNTN_CD,
  idt.CVRD_LVL_CARE_THRU_DT + bm.date_shift_days CVRD_LVL_CARE_THRU_DT,
  idt.BENE_DEATH_DT + bm.date_shift_days BENE_DEATH_DT,
  idt.BENE_DEATH_DT_VRFY_CD,
  idt.ADMSN_DEATH_DAY_CNT,
  idt.INTRNL_USE_SSI_IND_CD,
  idt.INTRNL_USE_SSI_DAY_CNT,
  idt.INTRNL_USE_SSI_DATA,
  idt.INTRNL_USE_IPSB_CD,
  idt.INTRNL_USE_FIL_DT_CD,
  idt.INTRNL_USE_SMPL_SIZE_CD,
  idt.LOS_DAY_CNT,
  idt.OUTLIER_DAY_CNT,
  idt.UTLZTN_DAY_CNT,
  idt.TOT_COINSRNC_DAY_CNT,
  idt.BENE_LRD_USE_CNT,
  idt.BENE_PTA_COINSRNC_AMT,
  idt.BENE_IP_DDCTBL_AMT,
  idt.BENE_BLOOD_DDCTBL_AMT,
  idt.BENE_PRMRY_PYR_CD,
  idt.BENE_PRMRY_PYR_AMT,
  idt.DRG_CD,
  idt.DRG_OUTLIER_STAY_CD,
  idt.DRG_OUTLIER_PMT_AMT,
  idt.DRG_PRICE_AMT,
  idt.IP_DSPRPRTNT_SHR_AMT,
  idt.IME_AMT,
  idt.PASS_THRU_AMT,
  idt.TOT_PPS_CPTL_AMT,
  idt.IP_LOW_VOL_PYMT_AMT,
  idt.TOT_CHRG_AMT,
  idt.TOT_CVR_CHRG_AMT,
  idt.MDCR_PMT_AMT,
  idt.ACMDTNS_TOT_CHRG_AMT,
  idt.DPRTMNTL_TOT_CHRG_AMT,
  idt.PRVT_ROOM_DAY_CNT,
  idt.SEMIPRVT_ROOM_DAY_CNT,
  idt.WARD_DAY_CNT,
  idt.INTNSV_CARE_DAY_CNT,
  idt.CRNRY_CARE_DAY_CNT,
  idt.PRVT_ROOM_CHRG_AMT,
  idt.SEMIPRVT_ROOM_CHRG_AMT,
  idt.WARD_CHRG_AMT,
  idt.INTNSV_CARE_CHRG_AMT,
  idt.CRNRY_CARE_CHRG_AMT,
  idt.OTHR_SRVC_CHRG_AMT,
  idt.PHRMCY_CHRG_AMT,
  idt.MDCL_SUPLY_CHRG_AMT,
  idt.DME_CHRG_AMT,
  idt.USED_DME_CHRG_AMT,
  idt.PHYS_THRPY_CHRG_AMT,
  idt.OCPTNL_THRPY_CHRG_AMT,
  idt.SPCH_PTHLGY_CHRG_AMT,
  idt.INHLTN_THRPY_CHRG_AMT,
  idt.BLOOD_CHRG_AMT,
  idt.BLOOD_ADMIN_CHRG_AMT,
  idt.BLOOD_PT_FRNSH_QTY,
  idt.OPRTG_ROOM_CHRG_AMT,
  idt.LTHTRPSY_CHRG_AMT,
  idt.CRDLGY_CHRG_AMT,
  idt.ANSTHSA_CHRG_AMT,
  idt.LAB_CHRG_AMT,
  idt.RDLGY_CHRG_AMT,
  idt.MRI_CHRG_AMT,
  idt.OP_SRVC_CHRG_AMT,
  idt.ER_CHRG_AMT,
  idt.AMBLNC_CHRG_AMT,
  idt.PROFNL_FEES_CHRG_AMT,
  idt.ORGN_ACQSTN_CHRG_AMT,
  idt.ESRD_REV_SETG_CHRG_AMT,
  idt.CLNC_VISIT_CHRG_AMT,
  idt.ICU_IND_CD,
  idt.CRNRY_CARE_IND_CD,
  idt.PHRMCY_IND_CD,
  idt.TRNSPLNT_IND_CD,
  idt.RDLGY_ONCLGY_IND_SW,
  idt.RDLGY_DGNSTC_IND_SW,
  idt.RDLGY_THRPTC_IND_SW,
  idt.RDLGY_NUCLR_MDCN_IND_SW,
  idt.RDLGY_CT_SCAN_IND_SW,
  idt.RDLGY_OTHR_IMGNG_IND_SW,
  idt.OP_SRVC_IND_CD,
  idt.ORGN_ACQSTN_IND_CD,
  idt.ESRD_COND_CD,
  idt.ESRD_SETG_IND_1_CD,
  idt.ESRD_SETG_IND_2_CD,
  idt.ESRD_SETG_IND_3_CD,
  idt.ESRD_SETG_IND_4_CD,
  idt.ESRD_SETG_IND_5_CD,
  idt.ADMTG_DGNS_CD,
  idt.ADMTG_DGNS_VRSN_CD,
  idt.DGNS_CD_CNT,
  idt.DGNS_VRSN_CD,
  idt.DGNS_VRSN_CD_1,
  idt.DGNS_VRSN_CD_2,
  idt.DGNS_VRSN_CD_3,
  idt.DGNS_VRSN_CD_4,
  idt.DGNS_VRSN_CD_5,
  idt.DGNS_VRSN_CD_6,
  idt.DGNS_VRSN_CD_7,
  idt.DGNS_VRSN_CD_8,
  idt.DGNS_VRSN_CD_9,
  idt.DGNS_VRSN_CD_10,
  idt.DGNS_VRSN_CD_11,
  idt.DGNS_VRSN_CD_12,
  idt.DGNS_VRSN_CD_13,
  idt.DGNS_VRSN_CD_14,
  idt.DGNS_VRSN_CD_15,
  idt.DGNS_VRSN_CD_16,
  idt.DGNS_VRSN_CD_17,
  idt.DGNS_VRSN_CD_18,
  idt.DGNS_VRSN_CD_19,
  idt.DGNS_VRSN_CD_20,
  idt.DGNS_VRSN_CD_21,
  idt.DGNS_VRSN_CD_22,
  idt.DGNS_VRSN_CD_23,
  idt.DGNS_VRSN_CD_24,
  idt.DGNS_VRSN_CD_25,
  idt.DGNS_1_CD,
  idt.DGNS_2_CD,
  idt.DGNS_3_CD,
  idt.DGNS_4_CD,
  idt.DGNS_5_CD,
  idt.DGNS_6_CD,
  idt.DGNS_7_CD,
  idt.DGNS_8_CD,
  idt.DGNS_9_CD,
  idt.DGNS_10_CD,
  idt.DGNS_11_CD,
  idt.DGNS_12_CD,
  idt.DGNS_13_CD,
  idt.DGNS_14_CD,
  idt.DGNS_15_CD,
  idt.DGNS_16_CD,
  idt.DGNS_17_CD,
  idt.DGNS_18_CD,
  idt.DGNS_19_CD,
  idt.DGNS_20_CD,
  idt.DGNS_21_CD,
  idt.DGNS_22_CD,
  idt.DGNS_23_CD,
  idt.DGNS_24_CD,
  idt.DGNS_25_CD,
  idt.DGNS_POA_CD,
  idt.POA_DGNS_CD_CNT,
  idt.POA_DGNS_1_IND_CD,
  idt.POA_DGNS_2_IND_CD,
  idt.POA_DGNS_3_IND_CD,
  idt.POA_DGNS_4_IND_CD,
  idt.POA_DGNS_5_IND_CD,
  idt.POA_DGNS_6_IND_CD,
  idt.POA_DGNS_7_IND_CD,
  idt.POA_DGNS_8_IND_CD,
  idt.POA_DGNS_9_IND_CD,
  idt.POA_DGNS_10_IND_CD,
  idt.POA_DGNS_11_IND_CD,
  idt.POA_DGNS_12_IND_CD,
  idt.POA_DGNS_13_IND_CD,
  idt.POA_DGNS_14_IND_CD,
  idt.POA_DGNS_15_IND_CD,
  idt.POA_DGNS_16_IND_CD,
  idt.POA_DGNS_17_IND_CD,
  idt.POA_DGNS_18_IND_CD,
  idt.POA_DGNS_19_IND_CD,
  idt.POA_DGNS_20_IND_CD,
  idt.POA_DGNS_21_IND_CD,
  idt.POA_DGNS_22_IND_CD,
  idt.POA_DGNS_23_IND_CD,
  idt.POA_DGNS_24_IND_CD,
  idt.POA_DGNS_25_IND_CD,
  idt.DGNS_E_CD_CNT,
  idt.DGNS_E_VRSN_CD,
  idt.DGNS_E_VRSN_CD_1,
  idt.DGNS_E_VRSN_CD_2,
  idt.DGNS_E_VRSN_CD_3,
  idt.DGNS_E_VRSN_CD_4,
  idt.DGNS_E_VRSN_CD_5,
  idt.DGNS_E_VRSN_CD_6,
  idt.DGNS_E_VRSN_CD_7,
  idt.DGNS_E_VRSN_CD_8,
  idt.DGNS_E_VRSN_CD_9,
  idt.DGNS_E_VRSN_CD_10,
  idt.DGNS_E_VRSN_CD_11,
  idt.DGNS_E_VRSN_CD_12,
  idt.DGNS_E_1_CD,
  idt.DGNS_E_2_CD,
  idt.DGNS_E_3_CD,
  idt.DGNS_E_4_CD,
  idt.DGNS_E_5_CD,
  idt.DGNS_E_6_CD,
  idt.DGNS_E_7_CD,
  idt.DGNS_E_8_CD,
  idt.DGNS_E_9_CD,
  idt.DGNS_E_10_CD,
  idt.DGNS_E_11_CD,
  idt.DGNS_E_12_CD,
  idt.POA_DGNS_E_CD_CNT,
  idt.POA_DGNS_E_1_IND_CD,
  idt.POA_DGNS_E_2_IND_CD,
  idt.POA_DGNS_E_3_IND_CD,
  idt.POA_DGNS_E_4_IND_CD,
  idt.POA_DGNS_E_5_IND_CD,
  idt.POA_DGNS_E_6_IND_CD,
  idt.POA_DGNS_E_7_IND_CD,
  idt.POA_DGNS_E_8_IND_CD,
  idt.POA_DGNS_E_9_IND_CD,
  idt.POA_DGNS_E_10_IND_CD,
  idt.POA_DGNS_E_11_IND_CD,
  idt.POA_DGNS_E_12_IND_CD,
  idt.SRGCL_PRCDR_IND_SW,
  idt.SRGCL_PRCDR_CD_CNT,
  idt.SRGCL_PRCDR_VRSN_CD,
  idt.SRGCL_PRCDR_VRSN_CD_1,
  idt.SRGCL_PRCDR_VRSN_CD_2,
  idt.SRGCL_PRCDR_VRSN_CD_3,
  idt.SRGCL_PRCDR_VRSN_CD_4,
  idt.SRGCL_PRCDR_VRSN_CD_5,
  idt.SRGCL_PRCDR_VRSN_CD_6,
  idt.SRGCL_PRCDR_VRSN_CD_7,
  idt.SRGCL_PRCDR_VRSN_CD_8,
  idt.SRGCL_PRCDR_VRSN_CD_9,
  idt.SRGCL_PRCDR_VRSN_CD_10,
  idt.SRGCL_PRCDR_VRSN_CD_11,
  idt.SRGCL_PRCDR_VRSN_CD_12,
  idt.SRGCL_PRCDR_VRSN_CD_13,
  idt.SRGCL_PRCDR_VRSN_CD_14,
  idt.SRGCL_PRCDR_VRSN_CD_15,
  idt.SRGCL_PRCDR_VRSN_CD_16,
  idt.SRGCL_PRCDR_VRSN_CD_17,
  idt.SRGCL_PRCDR_VRSN_CD_18,
  idt.SRGCL_PRCDR_VRSN_CD_19,
  idt.SRGCL_PRCDR_VRSN_CD_20,
  idt.SRGCL_PRCDR_VRSN_CD_21,
  idt.SRGCL_PRCDR_VRSN_CD_22,
  idt.SRGCL_PRCDR_VRSN_CD_23,
  idt.SRGCL_PRCDR_VRSN_CD_24,
  idt.SRGCL_PRCDR_VRSN_CD_25,
  idt.SRGCL_PRCDR_1_CD,
  idt.SRGCL_PRCDR_2_CD,
  idt.SRGCL_PRCDR_3_CD,
  idt.SRGCL_PRCDR_4_CD,
  idt.SRGCL_PRCDR_5_CD,
  idt.SRGCL_PRCDR_6_CD,
  idt.SRGCL_PRCDR_7_CD,
  idt.SRGCL_PRCDR_8_CD,
  idt.SRGCL_PRCDR_9_CD,
  idt.SRGCL_PRCDR_10_CD,
  idt.SRGCL_PRCDR_11_CD,
  idt.SRGCL_PRCDR_12_CD,
  idt.SRGCL_PRCDR_13_CD,
  idt.SRGCL_PRCDR_14_CD,
  idt.SRGCL_PRCDR_15_CD,
  idt.SRGCL_PRCDR_16_CD,
  idt.SRGCL_PRCDR_17_CD,
  idt.SRGCL_PRCDR_18_CD,
  idt.SRGCL_PRCDR_19_CD,
  idt.SRGCL_PRCDR_20_CD,
  idt.SRGCL_PRCDR_21_CD,
  idt.SRGCL_PRCDR_22_CD,
  idt.SRGCL_PRCDR_23_CD,
  idt.SRGCL_PRCDR_24_CD,
  idt.SRGCL_PRCDR_25_CD,
  idt.SRGCL_PRCDR_DT_CNT,
  idt.SRGCL_PRCDR_PRFRM_1_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_1_DT,
  idt.SRGCL_PRCDR_PRFRM_2_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_2_DT,
  idt.SRGCL_PRCDR_PRFRM_3_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_3_DT,
  idt.SRGCL_PRCDR_PRFRM_4_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_4_DT,
  idt.SRGCL_PRCDR_PRFRM_5_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_5_DT,
  idt.SRGCL_PRCDR_PRFRM_6_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_6_DT,
  idt.SRGCL_PRCDR_PRFRM_7_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_7_DT,
  idt.SRGCL_PRCDR_PRFRM_8_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_8_DT,
  idt.SRGCL_PRCDR_PRFRM_9_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_9_DT,
  idt.SRGCL_PRCDR_PRFRM_10_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_10_DT,
  idt.SRGCL_PRCDR_PRFRM_11_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_11_DT,
  idt.SRGCL_PRCDR_PRFRM_12_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_12_DT,
  idt.SRGCL_PRCDR_PRFRM_13_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_13_DT,
  idt.SRGCL_PRCDR_PRFRM_14_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_14_DT,
  idt.SRGCL_PRCDR_PRFRM_15_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_15_DT,
  idt.SRGCL_PRCDR_PRFRM_16_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_16_DT,
  idt.SRGCL_PRCDR_PRFRM_17_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_17_DT,
  idt.SRGCL_PRCDR_PRFRM_18_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_18_DT,
  idt.SRGCL_PRCDR_PRFRM_19_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_19_DT,
  idt.SRGCL_PRCDR_PRFRM_20_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_20_DT,
  idt.SRGCL_PRCDR_PRFRM_21_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_21_DT,
  idt.SRGCL_PRCDR_PRFRM_22_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_22_DT,
  idt.SRGCL_PRCDR_PRFRM_23_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_23_DT,
  idt.SRGCL_PRCDR_PRFRM_24_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_24_DT,
  idt.SRGCL_PRCDR_PRFRM_25_DT + bm.date_shift_days SRGCL_PRCDR_PRFRM_25_DT,
  idt.CLM_PTNT_RLTNSHP_CD,
  idt.CARE_IMPRVMT_MODEL_1_CD,
  idt.CARE_IMPRVMT_MODEL_2_CD,
  idt.CARE_IMPRVMT_MODEL_3_CD,
  idt.CARE_IMPRVMT_MODEL_4_CD,
  idt.VBP_PRTCPNT_IND_CD,
  idt.HRR_PRTCPNT_IND_CD,
  idt.BNDLD_MODEL_DSCNT_PCT,
  idt.VBP_ADJSTMT_PCT,
  idt.HRR_ADJSTMT_PCT,
  idt.INFRMTL_ENCTR_IND_SW,
  idt.MA_TCHNG_IND_SW,
  idt.PROD_RPLCMT_LIFECYC_SW,
  idt.PROD_RPLCMT_RCLL_SW,
  idt.CRED_RCVD_RPLCD_DVC_SW,
  idt.OBSRVTN_SW,
  idt.NEW_TCHNLGY_ADD_ON_AMT,
  idt.BASE_OPRTG_DRG_AMT,
  idt.OPRTG_HSP_AMT,
  idt.MDCL_SRGCL_GNRL_AMT,
  idt.MDCL_SRGCL_NSTRL_AMT,
  idt.MDCL_SRGCL_STRL_AMT,
  idt.TAKE_HOME_AMT,
  idt.PRSTHTC_ORTHTC_AMT,
  idt.MDCL_SRGCL_PCMKR_AMT,
  idt.INTRAOCULAR_LENS_AMT,
  idt.OXYGN_TAKE_HOME_AMT,
  idt.OTHR_IMPLANTS_AMT,
  idt.OTHR_SUPLIES_DVC_AMT,
  idt.INCDNT_RDLGY_AMT,
  idt.INCDNT_DGNSTC_SRVCS_AMT,
  idt.MDCL_SRGCL_DRSNG_AMT,
  idt.INVSTGTNL_DVC_AMT,
  idt.MDCL_SRGCL_MISC_AMT,
  idt.RDLGY_ONCOLOGY_AMT,
  idt.RDLGY_DGNSTC_AMT,
  idt.RDLGY_THRPTC_AMT,
  idt.RDLGY_NUCLR_MDCN_AMT,
  idt.RDLGY_CT_SCAN_AMT,
  idt.RDLGY_OTHR_IMGNG_AMT,
  idt.OPRTG_ROOM_AMT,
  idt.OR_LABOR_DLVRY_AMT,
  idt.CRDC_CATHRZTN_AMT,
  idt.SQSTRTN_RDCTN_AMT,
  idt.UNCOMPD_CARE_PYMT_AMT,
  idt.BNDLD_ADJSTMT_AMT,
  idt.VBP_ADJSTMT_AMT,
  idt.HRR_ADJSTMT_AMT,
  idt.EHR_PYMT_ADJSTMT_AMT,
  idt.PPS_STD_VAL_PYMT_AMT,
  idt.FINL_STD_AMT,
  idt.IPPS_FLEX_PYMT_6_AMT,
  idt.IPPS_FLEX_PYMT_7_AMT,
  idt.PTNT_ADD_ON_PYMT_AMT,
  idt.HAC_PGM_RDCTN_IND_SW,
  idt.PGM_RDCTN_IND_SW,
  idt.PA_IND_CD,
  idt.UNIQ_TRKNG_NUM,
  idt.STAY_2_IND_SW
from medpar_all idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".maxdata_ip
select /*+ PARALLEL(maxdata_ip,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MSIS_ID,
  idt.STATE_CD,
  idt.YR_NUM,
  idt.EL_DOB + bm.date_shift_days EL_DOB,
  idt.EL_SEX_CD,
  idt.EL_RACE_ETHNCY_CD,
  idt.RACE_CODE_1,
  idt.RACE_CODE_2,
  idt.RACE_CODE_3,
  idt.RACE_CODE_4,
  idt.RACE_CODE_5,
  idt.ETHNICITY_CODE,
  idt.EL_SS_ELGBLTY_CD_LTST,
  idt.EL_SS_ELGBLTY_CD_MO,
  idt.EL_MAX_ELGBLTY_CD_LTST,
  idt.EL_MAX_ELGBLTY_CD_MO,
  idt.EL_MDCR_ANN_XOVR_OLD,
  idt.MSNG_ELG_DATA,
  idt.EL_MDCR_XOVR_CLM_BSD_CD,
  idt.EL_MDCR_ANN_XOVR_99,
  idt.MSIS_TOS,
  idt.MSIS_TOP,
  idt.MAX_TOS,
  idt.PRVDR_ID_NMBR,
  idt.NPI,
  idt.TAXONOMY,
  idt.TYPE_CLM_CD,
  idt.ADJUST_CD,
  idt.PHP_TYPE,
  idt.PHP_ID,
  idt.MDCD_PYMT_AMT,
  idt.TP_PYMT_AMT,
  idt.PYMT_DT + bm.date_shift_days PYMT_DT,
  idt.CHRG_AMT,
  idt.PHP_VAL,
  idt.MDCR_COINSUR_PYMT_AMT,
  idt.MDCR_DED_PYMT_AMT,
  idt.ADMSN_DT + bm.date_shift_days ADMSN_DT,
  idt.SRVC_BGN_DT + bm.date_shift_days SRVC_BGN_DT,
  idt.SRVC_END_DT + bm.date_shift_days SRVC_END_DT,
  idt.DIAG_CD_1,
  idt.DIAG_CD_2,
  idt.DIAG_CD_3,
  idt.DIAG_CD_4,
  idt.DIAG_CD_5,
  idt.DIAG_CD_6,
  idt.DIAG_CD_7,
  idt.DIAG_CD_8,
  idt.DIAG_CD_9,
  idt.PRNCPL_PRCDR_DT + bm.date_shift_days PRNCPL_PRCDR_DT,
  idt.PRCDR_CD_SYS_1,
  idt.PRCDR_CD_1,
  idt.PRCDR_CD_SYS_2,
  idt.PRCDR_CD_2,
  idt.PRCDR_CD_SYS_3,
  idt.PRCDR_CD_3,
  idt.PRCDR_CD_SYS_4,
  idt.PRCDR_CD_4,
  idt.PRCDR_CD_SYS_5,
  idt.PRCDR_CD_5,
  idt.PRCDR_CD_SYS_6,
  idt.PRCDR_CD_6,
  idt.RCPNT_DLVRY_CD,
  idt.MDCD_CVRD_IP_DAYS,
  idt.PATIENT_STATUS_CD,
  idt.DRG_REL_GROUP_IND,
  idt.DRG_REL_GROUP,
  idt.UB_92_REV_CD_GP_1,
  idt.UB_92_REV_CD_CHGS_1,
  idt.UB_92_REV_CD_UNITS_1,
  idt.UB_92_REV_CD_GP_2,
  idt.UB_92_REV_CD_CHGS_2,
  idt.UB_92_REV_CD_UNITS_2,
  idt.UB_92_REV_CD_GP_3,
  idt.UB_92_REV_CD_CHGS_3,
  idt.UB_92_REV_CD_UNITS_3,
  idt.UB_92_REV_CD_GP_4,
  idt.UB_92_REV_CD_CHGS_4,
  idt.UB_92_REV_CD_UNITS_4,
  idt.UB_92_REV_CD_GP_5,
  idt.UB_92_REV_CD_CHGS_5,
  idt.UB_92_REV_CD_UNITS_5,
  idt.UB_92_REV_CD_GP_6,
  idt.UB_92_REV_CD_CHGS_6,
  idt.UB_92_REV_CD_UNITS_6,
  idt.UB_92_REV_CD_GP_7,
  idt.UB_92_REV_CD_CHGS_7,
  idt.UB_92_REV_CD_UNITS_7,
  idt.UB_92_REV_CD_GP_8,
  idt.UB_92_REV_CD_CHGS_8,
  idt.UB_92_REV_CD_UNITS_8,
  idt.UB_92_REV_CD_GP_9,
  idt.UB_92_REV_CD_CHGS_9,
  idt.UB_92_REV_CD_UNITS_9,
  idt.UB_92_REV_CD_GP_10,
  idt.UB_92_REV_CD_CHGS_10,
  idt.UB_92_REV_CD_UNITS_10,
  idt.UB_92_REV_CD_GP_11,
  idt.UB_92_REV_CD_CHGS_11,
  idt.UB_92_REV_CD_UNITS_11,
  idt.UB_92_REV_CD_GP_12,
  idt.UB_92_REV_CD_CHGS_12,
  idt.UB_92_REV_CD_UNITS_12,
  idt.UB_92_REV_CD_GP_13,
  idt.UB_92_REV_CD_CHGS_13,
  idt.UB_92_REV_CD_UNITS_13,
  idt.UB_92_REV_CD_GP_14,
  idt.UB_92_REV_CD_CHGS_14,
  idt.UB_92_REV_CD_UNITS_14,
  idt.UB_92_REV_CD_GP_15,
  idt.UB_92_REV_CD_CHGS_15,
  idt.UB_92_REV_CD_UNITS_15,
  idt.UB_92_REV_CD_GP_16,
  idt.UB_92_REV_CD_CHGS_16,
  idt.UB_92_REV_CD_UNITS_16,
  idt.UB_92_REV_CD_GP_17,
  idt.UB_92_REV_CD_CHGS_17,
  idt.UB_92_REV_CD_UNITS_17,
  idt.UB_92_REV_CD_GP_18,
  idt.UB_92_REV_CD_CHGS_18,
  idt.UB_92_REV_CD_UNITS_18,
  idt.UB_92_REV_CD_GP_19,
  idt.UB_92_REV_CD_CHGS_19,
  idt.UB_92_REV_CD_UNITS_19,
  idt.UB_92_REV_CD_GP_20,
  idt.UB_92_REV_CD_CHGS_20,
  idt.UB_92_REV_CD_UNITS_20,
  idt.UB_92_REV_CD_GP_21,
  idt.UB_92_REV_CD_CHGS_21,
  idt.UB_92_REV_CD_UNITS_21,
  idt.UB_92_REV_CD_GP_22,
  idt.UB_92_REV_CD_CHGS_22,
  idt.UB_92_REV_CD_UNITS_22,
  idt.UB_92_REV_CD_GP_23,
  idt.UB_92_REV_CD_CHGS_23,
  idt.UB_92_REV_CD_UNITS_23
from maxdata_ip idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_revenue_center
select /*+ PARALLEL(hha_revenue_center,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.CLM_LINE_NUM,
  idt.NCH_CLM_TYPE_CD,
  idt.REV_CNTR,
  idt.REV_CNTR_DT + bm.date_shift_days REV_CNTR_DT,
  idt.REV_CNTR_1ST_ANSI_CD,
  idt.REV_CNTR_APC_HIPPS_CD,
  idt.HCPCS_CD,
  idt.HCPCS_1ST_MDFR_CD,
  idt.HCPCS_2ND_MDFR_CD,
  idt.REV_CNTR_PMT_MTHD_IND_CD,
  idt.REV_CNTR_UNIT_CNT,
  idt.REV_CNTR_RATE_AMT,
  idt.REV_CNTR_PMT_AMT_AMT,
  idt.REV_CNTR_TOT_CHRG_AMT,
  idt.REV_CNTR_NCVRD_CHRG_AMT,
  idt.REV_CNTR_DDCTBL_COINSRNC_CD,
  idt.REV_CNTR_STUS_IND_CD,
  idt.REV_CNTR_NDC_QTY,
  idt.REV_CNTR_NDC_QTY_QLFR_CD,
  idt.RNDRNG_PHYSN_UPIN,
  idt.RNDRNG_PHYSN_NPI
from hha_revenue_center idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_value_codes
select /*+ PARALLEL(hospice_value_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_VAL_CD_SEQ,
  idt.CLM_VAL_CD,
  idt.CLM_VAL_AMT
from hospice_value_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_condition_codes
select /*+ PARALLEL(hospice_condition_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_COND_CD_SEQ,
  idt.CLM_RLT_COND_CD
from hospice_condition_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".outpatient_revenue_center
select /*+ PARALLEL(outpatient_revenue_center,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.CLM_LINE_NUM,
  idt.NCH_CLM_TYPE_CD,
  idt.REV_CNTR,
  idt.REV_CNTR_DT + bm.date_shift_days REV_CNTR_DT,
  idt.REV_CNTR_1ST_ANSI_CD,
  idt.REV_CNTR_2ND_ANSI_CD,
  idt.REV_CNTR_3RD_ANSI_CD,
  idt.REV_CNTR_4TH_ANSI_CD,
  idt.REV_CNTR_APC_HIPPS_CD,
  idt.HCPCS_CD,
  idt.HCPCS_1ST_MDFR_CD,
  idt.HCPCS_2ND_MDFR_CD,
  idt.REV_CNTR_PMT_MTHD_IND_CD,
  idt.REV_CNTR_DSCNT_IND_CD,
  idt.REV_CNTR_PACKG_IND_CD,
  idt.REV_CNTR_OTAF_PMT_CD,
  idt.REV_CNTR_IDE_NDC_UPC_NUM,
  idt.REV_CNTR_UNIT_CNT,
  idt.REV_CNTR_RATE_AMT,
  idt.REV_CNTR_BLOOD_DDCTBL_AMT,
  idt.REV_CNTR_CASH_DDCTBL_AMT,
  idt.REV_CNTR_COINSRNC_WGE_ADJSTD_C,
  idt.REV_CNTR_RDCD_COINSRNC_AMT,
  idt.REV_CNTR_1ST_MSP_PD_AMT,
  idt.REV_CNTR_2ND_MSP_PD_AMT,
  idt.REV_CNTR_PRVDR_PMT_AMT,
  idt.REV_CNTR_BENE_PMT_AMT,
  idt.REV_CNTR_PTNT_RSPNSBLTY_PMT,
  idt.REV_CNTR_PMT_AMT_AMT,
  idt.REV_CNTR_TOT_CHRG_AMT,
  idt.REV_CNTR_NCVRD_CHRG_AMT,
  idt.REV_CNTR_STUS_IND_CD,
  idt.REV_CNTR_NDC_QTY,
  idt.REV_CNTR_NDC_QTY_QLFR_CD,
  idt.RNDRNG_PHYSN_UPIN,
  idt.RNDRNG_PHYSN_NPI
from outpatient_revenue_center idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".outpatient_value_codes
select /*+ PARALLEL(outpatient_value_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_VAL_CD_SEQ,
  idt.CLM_VAL_CD,
  idt.CLM_VAL_AMT
from outpatient_value_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".maxdata_rx
select /*+ PARALLEL(maxdata_rx,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MSIS_ID,
  idt.STATE_CD,
  idt.YR_NUM,
  idt.EL_DOB + bm.date_shift_days EL_DOB,
  idt.EL_SEX_CD,
  idt.EL_RACE_ETHNCY_CD,
  idt.RACE_CODE_1,
  idt.RACE_CODE_2,
  idt.RACE_CODE_3,
  idt.RACE_CODE_4,
  idt.RACE_CODE_5,
  idt.ETHNICITY_CODE,
  idt.EL_SS_ELGBLTY_CD_LTST,
  idt.EL_SS_ELGBLTY_CD_MO,
  idt.EL_MAX_ELGBLTY_CD_LTST,
  idt.EL_MAX_ELGBLTY_CD_MO,
  idt.EL_MDCR_ANN_XOVR_OLD,
  idt.EL_MDCR_XOVR_CLM_BSD_CD,
  idt.MSNG_ELG_DATA,
  idt.EL_MDCR_ANN_XOVR_99,
  idt.MSIS_TOS,
  idt.MSIS_TOP,
  idt.MAX_TOS,
  idt.PRVDR_ID_NMBR,
  idt.NPI,
  idt.TAXONOMY,
  idt.TYPE_CLM_CD,
  idt.ADJUST_CD,
  idt.PHP_TYPE,
  idt.PHP_ID,
  idt.MDCD_PYMT_AMT,
  idt.TP_PYMT_AMT,
  idt.PYMT_DT + bm.date_shift_days PYMT_DT,
  idt.CHRG_AMT,
  idt.PHP_VAL,
  idt.MDCR_COINSUR_PYMT_AMT,
  idt.MDCR_DED_PYMT_AMT,
  idt.PRES_PHYSICIAN_ID_NUM,
  idt.PRSC_WRTE_DT + bm.date_shift_days PRSC_WRTE_DT,
  idt.PRSCRPTN_FILL_DT + bm.date_shift_days PRSCRPTN_FILL_DT,
  idt.NEW_REFILL_IND,
  idt.NDC,
  idt.QTY_SRVC_UNITS,
  idt.DAYS_SUPPLY
from maxdata_rx idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".bcarrier_line
select /*+ PARALLEL(bcarrier_line,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.LINE_NUM,
  idt.NCH_CLM_TYPE_CD,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.CARR_PRFRNG_PIN_NUM,
  idt.PRF_PHYSN_UPIN,
  idt.PRF_PHYSN_NPI,
  idt.ORG_NPI_NUM,
  idt.CARR_LINE_PRVDR_TYPE_CD,
  idt.TAX_NUM,
  idt.PRVDR_STATE_CD,
  idt.PRVDR_ZIP,
  idt.PRVDR_SPCLTY,
  idt.PRTCPTNG_IND_CD,
  idt.CARR_LINE_RDCD_PMT_PHYS_ASTN_C,
  idt.LINE_SRVC_CNT,
  idt.LINE_CMS_TYPE_SRVC_CD,
  idt.LINE_PLACE_OF_SRVC_CD,
  idt.CARR_LINE_PRCNG_LCLTY_CD,
  idt.LINE_1ST_EXPNS_DT + bm.date_shift_days LINE_1ST_EXPNS_DT,
  idt.LINE_LAST_EXPNS_DT + bm.date_shift_days LINE_LAST_EXPNS_DT,
  idt.HCPCS_CD,
  idt.HCPCS_1ST_MDFR_CD,
  idt.HCPCS_2ND_MDFR_CD,
  idt.BETOS_CD,
  idt.LINE_NCH_PMT_AMT,
  idt.LINE_BENE_PMT_AMT,
  idt.LINE_PRVDR_PMT_AMT,
  idt.LINE_BENE_PTB_DDCTBL_AMT,
  idt.LINE_BENE_PRMRY_PYR_CD,
  idt.LINE_BENE_PRMRY_PYR_PD_AMT,
  idt.LINE_COINSRNC_AMT,
  idt.LINE_SBMTD_CHRG_AMT,
  idt.LINE_ALOWD_CHRG_AMT,
  idt.LINE_PRCSG_IND_CD,
  idt.LINE_PMT_80_100_CD,
  idt.LINE_SERVICE_DEDUCTIBLE,
  idt.CARR_LINE_MTUS_CNT,
  idt.CARR_LINE_MTUS_CD,
  idt.LINE_ICD_DGNS_CD,
  idt.LINE_ICD_DGNS_VRSN_CD,
  idt.HPSA_SCRCTY_IND_CD,
  idt.CARR_LINE_RX_NUM,
  idt.LINE_HCT_HGB_RSLT_NUM,
  idt.LINE_HCT_HGB_TYPE_CD,
  idt.LINE_NDC_CD,
  idt.CARR_LINE_CLIA_LAB_NUM,
  idt.CARR_LINE_ANSTHSA_UNIT_CNT
from bcarrier_line idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".maxdata_lt
select /*+ PARALLEL(maxdata_lt,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.MSIS_ID,
  idt.STATE_CD,
  idt.YR_NUM,
  idt.EL_DOB + bm.date_shift_days EL_DOB,
  idt.EL_SEX_CD,
  idt.EL_RACE_ETHNCY_CD,
  idt.RACE_CODE_1,
  idt.RACE_CODE_2,
  idt.RACE_CODE_3,
  idt.RACE_CODE_4,
  idt.RACE_CODE_5,
  idt.ETHNICITY_CODE,
  idt.EL_SS_ELGBLTY_CD_LTST,
  idt.EL_SS_ELGBLTY_CD_MO,
  idt.EL_MAX_ELGBLTY_CD_LTST,
  idt.EL_MAX_ELGBLTY_CD_MO,
  idt.EL_MDCR_ANN_XOVR_OLD,
  idt.MSNG_ELG_DATA,
  idt.EL_MDCR_XOVR_CLM_BSD_CD,
  idt.EL_MDCR_ANN_XOVR_99,
  idt.MSIS_TOS,
  idt.MSIS_TOP,
  idt.MAX_TOS,
  idt.PRVDR_ID_NMBR,
  idt.NPI,
  idt.TAXONOMY,
  idt.TYPE_CLM_CD,
  idt.ADJUST_CD,
  idt.PHP_TYPE,
  idt.PHP_ID,
  idt.MDCD_PYMT_AMT,
  idt.TP_PYMT_AMT,
  idt.PYMT_DT + bm.date_shift_days PYMT_DT,
  idt.CHRG_AMT,
  idt.PHP_VAL,
  idt.MDCR_COINSUR_PYMT_AMT,
  idt.MDCR_DED_PYMT_AMT,
  idt.ADMSN_DT + bm.date_shift_days ADMSN_DT,
  idt.SRVC_BGN_DT + bm.date_shift_days SRVC_BGN_DT,
  idt.SRVC_END_DT + bm.date_shift_days SRVC_END_DT,
  idt.DIAG_CD_1,
  idt.DIAG_CD_2,
  idt.DIAG_CD_3,
  idt.DIAG_CD_4,
  idt.DIAG_CD_5,
  idt.MDCD_CVRD_MENTL_DAY_CNT,
  idt.MDCD_CVRD_PSYCH_DAY_CNT,
  idt.INTRMDT_FAC_MR_DAY_CNT,
  idt.NRSNG_FAC_DAY_CNT,
  idt.LT_CARE_LVE_DAY_CNT,
  idt.PATIENT_STATUS_CD,
  idt.PATIENT_LIB_AMT
from maxdata_lt idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_base_claims
select /*+ PARALLEL(hha_base_claims,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_NEAR_LINE_REC_IDENT_CD,
  idt.NCH_CLM_TYPE_CD,
  idt.CLM_FROM_DT + bm.date_shift_days CLM_FROM_DT,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.NCH_WKLY_PROC_DT + bm.date_shift_days NCH_WKLY_PROC_DT,
  idt.FI_CLM_PROC_DT + bm.date_shift_days FI_CLM_PROC_DT,
  idt.PRVDR_NUM,
  idt.CLM_FAC_TYPE_CD,
  idt.CLM_SRVC_CLSFCTN_TYPE_CD,
  idt.CLM_FREQ_CD,
  idt.FI_NUM,
  idt.CLM_MDCR_NON_PMT_RSN_CD,
  idt.CLM_PMT_AMT,
  idt.NCH_PRMRY_PYR_CLM_PD_AMT,
  idt.NCH_PRMRY_PYR_CD,
  idt.PRVDR_STATE_CD,
  idt.ORG_NPI_NUM,
  idt.AT_PHYSN_UPIN,
  idt.AT_PHYSN_NPI,
  idt.PTNT_DSCHRG_STUS_CD,
  idt.CLM_PPS_IND_CD,
  idt.CLM_TOT_CHRG_AMT,
  idt.PRNCPAL_DGNS_CD,
  idt.PRNCPAL_DGNS_VRSN_CD,
  idt.ICD_DGNS_CD1,
  idt.ICD_DGNS_VRSN_CD1,
  idt.ICD_DGNS_CD2,
  idt.ICD_DGNS_VRSN_CD2,
  idt.ICD_DGNS_CD3,
  idt.ICD_DGNS_VRSN_CD3,
  idt.ICD_DGNS_CD4,
  idt.ICD_DGNS_VRSN_CD4,
  idt.ICD_DGNS_CD5,
  idt.ICD_DGNS_VRSN_CD5,
  idt.ICD_DGNS_CD6,
  idt.ICD_DGNS_VRSN_CD6,
  idt.ICD_DGNS_CD7,
  idt.ICD_DGNS_VRSN_CD7,
  idt.ICD_DGNS_CD8,
  idt.ICD_DGNS_VRSN_CD8,
  idt.ICD_DGNS_CD9,
  idt.ICD_DGNS_VRSN_CD9,
  idt.ICD_DGNS_CD10,
  idt.ICD_DGNS_VRSN_CD10,
  idt.ICD_DGNS_CD11,
  idt.ICD_DGNS_VRSN_CD11,
  idt.ICD_DGNS_CD12,
  idt.ICD_DGNS_VRSN_CD12,
  idt.ICD_DGNS_CD13,
  idt.ICD_DGNS_VRSN_CD13,
  idt.ICD_DGNS_CD14,
  idt.ICD_DGNS_VRSN_CD14,
  idt.ICD_DGNS_CD15,
  idt.ICD_DGNS_VRSN_CD15,
  idt.ICD_DGNS_CD16,
  idt.ICD_DGNS_VRSN_CD16,
  idt.ICD_DGNS_CD17,
  idt.ICD_DGNS_VRSN_CD17,
  idt.ICD_DGNS_CD18,
  idt.ICD_DGNS_VRSN_CD18,
  idt.ICD_DGNS_CD19,
  idt.ICD_DGNS_VRSN_CD19,
  idt.ICD_DGNS_CD20,
  idt.ICD_DGNS_VRSN_CD20,
  idt.ICD_DGNS_CD21,
  idt.ICD_DGNS_VRSN_CD21,
  idt.ICD_DGNS_CD22,
  idt.ICD_DGNS_VRSN_CD22,
  idt.ICD_DGNS_CD23,
  idt.ICD_DGNS_VRSN_CD23,
  idt.ICD_DGNS_CD24,
  idt.ICD_DGNS_VRSN_CD24,
  idt.ICD_DGNS_CD25,
  idt.ICD_DGNS_VRSN_CD25,
  idt.FST_DGNS_E_CD,
  idt.FST_DGNS_E_VRSN_CD,
  idt.ICD_DGNS_E_CD1,
  idt.ICD_DGNS_E_VRSN_CD1,
  idt.ICD_DGNS_E_CD2,
  idt.ICD_DGNS_E_VRSN_CD2,
  idt.ICD_DGNS_E_CD3,
  idt.ICD_DGNS_E_VRSN_CD3,
  idt.ICD_DGNS_E_CD4,
  idt.ICD_DGNS_E_VRSN_CD4,
  idt.ICD_DGNS_E_CD5,
  idt.ICD_DGNS_E_VRSN_CD5,
  idt.ICD_DGNS_E_CD6,
  idt.ICD_DGNS_E_VRSN_CD6,
  idt.ICD_DGNS_E_CD7,
  idt.ICD_DGNS_E_VRSN_CD7,
  idt.ICD_DGNS_E_CD8,
  idt.ICD_DGNS_E_VRSN_CD8,
  idt.ICD_DGNS_E_CD9,
  idt.ICD_DGNS_E_VRSN_CD9,
  idt.ICD_DGNS_E_CD10,
  idt.ICD_DGNS_E_VRSN_CD10,
  idt.ICD_DGNS_E_CD11,
  idt.ICD_DGNS_E_VRSN_CD11,
  idt.ICD_DGNS_E_CD12,
  idt.ICD_DGNS_E_VRSN_CD12,
  idt.CLM_HHA_LUPA_IND_CD,
  idt.CLM_HHA_RFRL_CD,
  idt.CLM_HHA_TOT_VISIT_CNT,
  idt.CLM_ADMSN_DT + bm.date_shift_days CLM_ADMSN_DT,
  idt.DOB_DT + bm.date_shift_days DOB_DT,
  idt.GNDR_CD,
  idt.BENE_RACE_CD,
  idt.BENE_CNTY_CD,
  idt.BENE_STATE_CD,
  NULL BENE_MLG_CNTCT_ZIP_CD,
  idt.CLM_MDCL_REC
from hha_base_claims idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_revenue_center
select /*+ PARALLEL(hospice_revenue_center,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.CLM_LINE_NUM,
  idt.NCH_CLM_TYPE_CD,
  idt.REV_CNTR,
  idt.REV_CNTR_DT + bm.date_shift_days REV_CNTR_DT,
  idt.HCPCS_CD,
  idt.HCPCS_1ST_MDFR_CD,
  idt.HCPCS_2ND_MDFR_CD,
  idt.REV_CNTR_UNIT_CNT,
  idt.REV_CNTR_RATE_AMT,
  idt.REV_CNTR_PRVDR_PMT_AMT,
  idt.REV_CNTR_BENE_PMT_AMT,
  idt.REV_CNTR_PMT_AMT_AMT,
  idt.REV_CNTR_TOT_CHRG_AMT,
  idt.REV_CNTR_NCVRD_CHRG_AMT,
  idt.REV_CNTR_DDCTBL_COINSRNC_CD,
  idt.REV_CNTR_NDC_QTY,
  idt.REV_CNTR_NDC_QTY_QLFR_CD,
  idt.RNDRNG_PHYSN_UPIN,
  idt.RNDRNG_PHYSN_NPI
from hospice_revenue_center idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_span_codes
select /*+ PARALLEL(hha_span_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_SPAN_CD_SEQ,
  idt.CLM_SPAN_CD,
  idt.CLM_SPAN_FROM_DT + bm.date_shift_days CLM_SPAN_FROM_DT,
  idt.CLM_SPAN_THRU_DT + bm.date_shift_days CLM_SPAN_THRU_DT
from hha_span_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_span_codes
select /*+ PARALLEL(hospice_span_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_SPAN_CD_SEQ,
  idt.CLM_SPAN_CD,
  idt.CLM_SPAN_FROM_DT + bm.date_shift_days CLM_SPAN_FROM_DT,
  idt.CLM_SPAN_THRU_DT + bm.date_shift_days CLM_SPAN_THRU_DT
from hospice_span_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".pde_saf
select /*+ PARALLEL(pde_saf,12) */ 
  idt.PDE_ID,
  bm.BENE_ID_DEID BENE_ID,
  idt.SRVC_DT + bm.date_shift_days SRVC_DT,
  idt.SRVC_PRVDR_ID_QLFYR_CD,
  idt.SRVC_PRVDR_ID,
  idt.PRSCRBR_ID_QLFYR_CD,
  idt.PRSCRBR_ID,
  idt.PROD_SRVC_ID,
  idt.DAW_PROD_SLCTN_CD,
  idt.QTY_DSPNSD_NUM,
  idt.DAYS_SUPLY_NUM,
  idt.DSPNSNG_STUS_CD,
  idt.DRUG_CVRG_STUS_CD,
  idt.GDC_BLW_OOPT_AMT,
  idt.GDC_ABV_OOPT_AMT,
  idt.PTNT_PAY_AMT,
  idt.OTHR_TROOP_AMT,
  idt.LICS_AMT,
  idt.PLRO_AMT,
  idt.CVRD_D_PLAN_PD_AMT,
  idt.NCVRD_PLAN_PD_AMT,
  idt.TOT_RX_CST_AMT,
  idt.BN,
  idt.GCDF,
  idt.GCDF_DESC,
  idt.STR,
  idt.GNN,
  idt.BENEFIT_PHASE
from pde_saf idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_condition_codes
select /*+ PARALLEL(hha_condition_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_COND_CD_SEQ,
  idt.CLM_RLT_COND_CD
from hha_condition_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".mbsf_d_cmpnts
select /*+ PARALLEL(mbsf_d_cmpnts,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.BENE_ENROLLMT_REF_YR,
  idt.CRDTBL_CVRG_SW,
  idt.PLAN_CVRG_MOS_NUM,
  idt.RDS_CVRG_MOS_NUM,
  idt.DUAL_ELGBL_MOS_NUM,
  idt.PTD_CNTRCT_ID_01,
  idt.PTD_CNTRCT_ID_02,
  idt.PTD_CNTRCT_ID_03,
  idt.PTD_CNTRCT_ID_04,
  idt.PTD_CNTRCT_ID_05,
  idt.PTD_CNTRCT_ID_06,
  idt.PTD_CNTRCT_ID_07,
  idt.PTD_CNTRCT_ID_08,
  idt.PTD_CNTRCT_ID_09,
  idt.PTD_CNTRCT_ID_10,
  idt.PTD_CNTRCT_ID_11,
  idt.PTD_CNTRCT_ID_12,
  idt.PTD_PBP_ID_01,
  idt.PTD_PBP_ID_02,
  idt.PTD_PBP_ID_03,
  idt.PTD_PBP_ID_04,
  idt.PTD_PBP_ID_05,
  idt.PTD_PBP_ID_06,
  idt.PTD_PBP_ID_07,
  idt.PTD_PBP_ID_08,
  idt.PTD_PBP_ID_09,
  idt.PTD_PBP_ID_10,
  idt.PTD_PBP_ID_11,
  idt.PTD_PBP_ID_12,
  idt.PTD_SGMT_ID_01,
  idt.PTD_SGMT_ID_02,
  idt.PTD_SGMT_ID_03,
  idt.PTD_SGMT_ID_04,
  idt.PTD_SGMT_ID_05,
  idt.PTD_SGMT_ID_06,
  idt.PTD_SGMT_ID_07,
  idt.PTD_SGMT_ID_08,
  idt.PTD_SGMT_ID_09,
  idt.PTD_SGMT_ID_10,
  idt.PTD_SGMT_ID_11,
  idt.PTD_SGMT_ID_12,
  idt.CST_SHR_GRP_CD_01,
  idt.CST_SHR_GRP_CD_02,
  idt.CST_SHR_GRP_CD_03,
  idt.CST_SHR_GRP_CD_04,
  idt.CST_SHR_GRP_CD_05,
  idt.CST_SHR_GRP_CD_06,
  idt.CST_SHR_GRP_CD_07,
  idt.CST_SHR_GRP_CD_08,
  idt.CST_SHR_GRP_CD_09,
  idt.CST_SHR_GRP_CD_10,
  idt.CST_SHR_GRP_CD_11,
  idt.CST_SHR_GRP_CD_12,
  idt.RDS_IND_01,
  idt.RDS_IND_02,
  idt.RDS_IND_03,
  idt.RDS_IND_04,
  idt.RDS_IND_05,
  idt.RDS_IND_06,
  idt.RDS_IND_07,
  idt.RDS_IND_08,
  idt.RDS_IND_09,
  idt.RDS_IND_10,
  idt.RDS_IND_11,
  idt.RDS_IND_12,
  idt.DUAL_STUS_CD_01,
  idt.DUAL_STUS_CD_02,
  idt.DUAL_STUS_CD_03,
  idt.DUAL_STUS_CD_04,
  idt.DUAL_STUS_CD_05,
  idt.DUAL_STUS_CD_06,
  idt.DUAL_STUS_CD_07,
  idt.DUAL_STUS_CD_08,
  idt.DUAL_STUS_CD_09,
  idt.DUAL_STUS_CD_10,
  idt.DUAL_STUS_CD_11,
  idt.DUAL_STUS_CD_12
from mbsf_d_cmpnts idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hospice_occurrnce_codes
select /*+ PARALLEL(hospice_occurrnce_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_OCRNC_CD_SEQ,
  idt.CLM_RLT_OCRNC_CD,
  idt.CLM_RLT_OCRNC_DT + bm.date_shift_days CLM_RLT_OCRNC_DT
from hospice_occurrnce_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_value_codes
select /*+ PARALLEL(hha_value_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_VAL_CD_SEQ,
  idt.CLM_VAL_CD,
  idt.CLM_VAL_AMT
from hha_value_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".bcarrier_claims
select /*+ PARALLEL(bcarrier_claims,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_NEAR_LINE_REC_IDENT_CD,
  idt.NCH_CLM_TYPE_CD,
  idt.CLM_FROM_DT + bm.date_shift_days CLM_FROM_DT,
  idt.CLM_THRU_DT + bm.date_shift_days CLM_THRU_DT,
  idt.NCH_WKLY_PROC_DT + bm.date_shift_days NCH_WKLY_PROC_DT,
  idt.CARR_CLM_ENTRY_CD,
  idt.CLM_DISP_CD,
  idt.CARR_NUM,
  idt.CARR_CLM_PMT_DNL_CD,
  idt.CLM_PMT_AMT,
  idt.CARR_CLM_PRMRY_PYR_PD_AMT,
  idt.RFR_PHYSN_UPIN,
  idt.RFR_PHYSN_NPI,
  idt.CARR_CLM_PRVDR_ASGNMT_IND_SW,
  idt.NCH_CLM_PRVDR_PMT_AMT,
  idt.NCH_CLM_BENE_PMT_AMT,
  idt.NCH_CARR_CLM_SBMTD_CHRG_AMT,
  idt.NCH_CARR_CLM_ALOWD_AMT,
  idt.CARR_CLM_CASH_DDCTBL_APLD_AMT,
  idt.CARR_CLM_HCPCS_YR_CD,
  idt.CARR_CLM_RFRNG_PIN_NUM,
  idt.PRNCPAL_DGNS_CD,
  idt.PRNCPAL_DGNS_VRSN_CD,
  idt.ICD_DGNS_CD1,
  idt.ICD_DGNS_VRSN_CD1,
  idt.ICD_DGNS_CD2,
  idt.ICD_DGNS_VRSN_CD2,
  idt.ICD_DGNS_CD3,
  idt.ICD_DGNS_VRSN_CD3,
  idt.ICD_DGNS_CD4,
  idt.ICD_DGNS_VRSN_CD4,
  idt.ICD_DGNS_CD5,
  idt.ICD_DGNS_VRSN_CD5,
  idt.ICD_DGNS_CD6,
  idt.ICD_DGNS_VRSN_CD6,
  idt.ICD_DGNS_CD7,
  idt.ICD_DGNS_VRSN_CD7,
  idt.ICD_DGNS_CD8,
  idt.ICD_DGNS_VRSN_CD8,
  idt.ICD_DGNS_CD9,
  idt.ICD_DGNS_VRSN_CD9,
  idt.ICD_DGNS_CD10,
  idt.ICD_DGNS_VRSN_CD10,
  idt.ICD_DGNS_CD11,
  idt.ICD_DGNS_VRSN_CD11,
  idt.ICD_DGNS_CD12,
  idt.ICD_DGNS_VRSN_CD12,
  idt.CLM_CLNCL_TRIL_NUM,
  idt.DOB_DT + bm.date_shift_days DOB_DT,
  idt.GNDR_CD,
  idt.BENE_RACE_CD,
  idt.BENE_CNTY_CD,
  idt.BENE_STATE_CD,
  NULL BENE_MLG_CNTCT_ZIP_CD
from bcarrier_claims idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".pde
select /*+ PARALLEL(pde,12) */ 
  idt.PDE_ID,
  bm.BENE_ID_DEID BENE_ID,
  idt.SRVC_DT + bm.date_shift_days SRVC_DT,
  idt.SRVC_PRVDR_ID_QLFYR_CD,
  idt.SRVC_PRVDR_ID,
  idt.PRSCRBR_ID_QLFYR_CD,
  idt.PRSCRBR_ID,
  idt.PROD_SRVC_ID,
  idt.DAW_PROD_SLCTN_CD,
  idt.QTY_DSPNSD_NUM,
  idt.DAYS_SUPLY_NUM,
  idt.DSPNSNG_STUS_CD,
  idt.DRUG_CVRG_STUS_CD,
  idt.GDC_BLW_OOPT_AMT,
  idt.GDC_ABV_OOPT_AMT,
  idt.PTNT_PAY_AMT,
  idt.OTHR_TROOP_AMT,
  idt.LICS_AMT,
  idt.PLRO_AMT,
  idt.CVRD_D_PLAN_PD_AMT,
  idt.NCVRD_PLAN_PD_AMT,
  idt.TOT_RX_CST_AMT,
  idt.BN,
  idt.GCDF,
  idt.GCDF_DESC,
  idt.STR,
  idt.GNN,
  idt.BENEFIT_PHASE
from pde idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;


insert /*+ APPEND */ into "&&deid_schema".hha_occurrnce_codes
select /*+ PARALLEL(hha_occurrnce_codes,12) */ 
  bm.BENE_ID_DEID BENE_ID,
  idt.CLM_ID,
  idt.NCH_CLM_TYPE_CD,
  idt.RLT_OCRNC_CD_SEQ,
  idt.CLM_RLT_OCRNC_CD,
  idt.CLM_RLT_OCRNC_DT + bm.date_shift_days CLM_RLT_OCRNC_DT
from hha_occurrnce_codes idt 
join bene_id_mapping bm on bm.bene_id = idt.bene_id;
commit;
